### ISSUE TITLE
Option to open in new window, or open multiple windows

### ISSUE THREAD

**Issue by alesdotio** [fitztrev/shuttle#1]
Hey, neat little app! It would be really cool if you could add some more options though. I would personally like if there was a way to open new terminal windows instead of tabs, or to even have one menu entry open multiple windows.

For example:

	"hosts": [
		{
			"name": "My Dev Server",
			"windows": [
				"ssh username@dev.example.com;",
				"cd ~/my-projects/whatever/;"
			]
		},
	]

which would open two windows, one sshing to the server and the other opening a local directory.

**Comment by thshdw** [comment]
@alesdotio see pull request https://github.com/fitztrev/shuttle/pull/104
adding isNewWindow: true to the command settings will open that command in a new window 

                                "name": "check shuttle process",
                                "isNewWindow": "true",
                                "cmd": "ps aux | grep [s]huttle"

**Comment by DemonTPx** [comment]
:+1:

**Comment by thshdw** [comment]
Complete! See release [v1.2.3](https://github.com/fitztrev/shuttle/releases/tag/v1.2.3)

**Comment by timothyallan** [comment]
Is there no option to open in tabs any more with 1.2.3?? I loved that. Now it either spits the command into the existing terminal, or opens a brand new instance which clutters up my environment depending on the inTerminal flag.

**Comment by thshdw** [comment]
@timothyallan If the inTerminal flag is missing then the default action is tabs. With the new version (if you are using iTerm, you must have the the ```  "iTerm_version": "stable",``` setting set to ```nightly``` or ```stable``` I'm working on the readme to explain all the new settings. Please let me know if you save questions.

**Comment by timothyallan** [comment]
That's why I'm here :) I got the new version, and noticed that it no longer opened new tabs. It would inject the next command into my currently open terminal window. I'd left my settings the same i.e. no inTerminal flag, as I'd not read the release notes and didn't even about it.

**Comment by thshdw** [comment]
@timothyallan Thanks for the update! :+1:  
Are you using iTerm or Terminal.app? 

Here is a draft of readme that explains the new settings:
https://github.com/thshdw/shuttle/blob/fix-editor-settings/README.md

**Comment by stephenhandley** [comment]
Looks like the original issue mentioned opening multiple windows/tabs with a single menu entry, but couldn't find anything in the [Command Settings wiki page](https://github.com/fitztrev/shuttle/wiki/Command-Settings) describing the syntax for that. Is that supported?

**Comment by thshdw** [comment]
@stephenhandley see here https://github.com/fitztrev/shuttle/wiki/Command-Settings#interminal-value

```"inTerminal": "new",```

```new``` opens the command in a new terminal window.

**Comment by stephenhandley** [comment]
@thshdw Thanks but I don't think that answers my question. I'm asking how to open 2 windows with one menue entry. For example, I want to open an ssh tunnel in one window and then run `psql ...` in another by selecting a single menu entry in shuttle. I don't anything in the docs or the section you linked that describes how to do that.

**Comment by thshdw** [comment]
@stephenhandley are you running the postgres command on the same server you are ssh'ing too?

**Comment by stephenhandley** [comment]
@thshdw nope running it locally. again this is just one example, I could think of others: open docker logs in one window and run tests on that container in another

**Comment by thshdw** [comment]
@stephenhandley Thanks for clarifying. Are you using iTerm and want these in multiple panes? Or are you using terminal and want them in separate windows?

**Comment by stephenhandley** [comment]
@thshdw i'm using terminal. multiple tabs within the same window would be awesome, but multiple windows works if the former isn't possible.

**Comment by thshdw** [comment]
@stephenhandley How would you feel about moving the conversation here: https://github.com/fitztrev/shuttle/issues/172

**Comment by stephenhandley** [comment]
@thshdw sounds good.
