### ISSUE TITLE
Edit link opens Parallels/Visual Studio by default

### ISSUE THREAD

**Issue by drakonka** [fitztrev/shuttle#105]
Clicking on "Edit" in "Settings" causes the file to be opened not in a present OS X editor like Sublime Text, but launch Parallels to open in Visual Studio. It seems Shuttle should prioritize local available editors before launching an alternative OS.

**Comment by thshdw** [comment]
Perhaps your default app for .json files is visual studio. In a terminal window type:
```
nano ~/Desktop/test.json
```
type something and save the file by pressing control + o
Right click on the file and click Get Info. Check the "Open With" settings to see if Sublime Text is the default app for the .json file type.

**Comment by drakonka** [comment]
My default is actually TextEdit, which seems to work fine with a manually created json file. However thinking about it you're probably right that this is some other local configuration issue on my end. I haven't had this problem with other json files before, but I did make a few random Parallels changes last week that maybe had some unintended consequences. I'll dig into it here.

Thanks!

**Comment by steffex** [comment]
@drakonka it could be your default external editor.

try `echo $EDITOR` in your terminal to see the current setting.

for example; i've set SublimeText as my default external editor by setting the next line in my .profile

`export EDITOR='subl -w'`

**Comment by thshdw** [comment]
@drakonka do you have any additional comments? This seems like a system issue. I wanted to make sure that you solved the problem before closing this issue.

**Comment by thshdw** [comment]
@drakonka I'm closing this out. If you feel it's still an shuttle issue and not a system issue please re-open! :smile:
