### ISSUE TITLE
Open ssh sessions using ssh://user@host handler

### ISSUE THREAD

**Issue by nigelm** [fitztrev/shuttle#106]
If ssh sessions were opened using a ssh:// url handler then, in iTerm at least, an extra layer of shell could be avoided, as well as making it very easy to use a specific ssh profile (again in iTerm).

Open ssh sessions via a url handler should also work in Terminal (Terminal is the default handler), although I have not tested this.

**Comment by thshdw** [comment]
Hello @nigelm I'm trying to understand your problem. 'm not sure I follow... by using ssh:// url handler what problem would that solve for you?

Thanks!

**Comment by thshdw** [comment]
@nigelm Could you elaborate? I'm trying to understand the issue.
