### ISSUE TITLE
Doesn't open terminal when using iTerm2 (nightly) and OSX 10.9

### ISSUE THREAD

**Issue by rafaqueque** [fitztrev/shuttle#107]
The title says it all.

**Comment by thshdw** [comment]
I think that this is because you need the reopen command in the apple script. 
~~~
         @"          tell the last session \n"
         @"              reopen \n"
~~~
This is working for me in the changes I made in pull request https://github.com/fitztrev/shuttle/pull/102

**Comment by DanyC97** [comment]
Few months back i looked at this issue and after my research and my discussion with ITerm developer i managed to understand the delta.

Basically in the ITerm nightly build, George refactored the AppleScript code as you can below

https://groups.google.com/forum/#!topic/iterm2-discuss/PcMGixwuceY

I have also raised the issue with Shuttle and you can see right at the bottom(last reply) that we should add a check to see if the ITerm version is a night build or not.

The refactored Shuttle's Apple Script code to work with the new format

https://groups.google.com/forum/#!topic/iterm2-discuss/z7zG34UCcXQ

In addition i have raised an issue on ITerm - the bahaviour has been changed a bit

https://code.google.com/p/iterm2/issues/detail?id=3219

**Comment by DanyC97** [comment]
It was my intention to make a pull request but unfortunately i never managed to build a Shuttle binary using XCODE to validate the changes, i'd love to be guided on how to do that.

Dani

**Comment by thshdw** [comment]
@rafaqueque @DanyC97 
I started a poll here https://plus.google.com/+MattTurner-ThShdwKnws/posts/akgb9gwrj8J

I'm curious to know which version of iTerm you would like to use with shuttle

**Comment by DanyC97** [comment]
Following the poll, has  anything else happened? Or no work started yet?

**Comment by thshdw** [comment]
@DanyC97 Eventually the applescript stuff will pull from a SQLite database. Thats a few months out. 

I do however plan to support iTerm Nightly by the end of the month. These changes will use the current applescript methods and wont have the SQLite support. Let me know if you have questions. Also feel free to email me, my contact info is on my github page. 

Thanks!

**Comment by thshdw** [comment]
Complete! See release [v1.2.3](https://github.com/fitztrev/shuttle/releases/tag/v1.2.3)
