### ISSUE TITLE
Feature: Search Box in menu

### ISSUE THREAD

**Issue by tkorkunckaya** [fitztrev/shuttle#108]
if you have many ssh entries in your menu, sub menus etc, it will be great if we have a search box to filter or find ssh entry like in spotlight.

**Comment by fitztrev** [comment]
Thanks for the idea! Will keep in mind for future release.

**Comment by shpoont** [comment]
This would be a great feature, I have a lot of entries in .shuttle.json and it already makes it hard to navigate through them.
