### ISSUE TITLE
Feature: Auto-refresh configuration

### ISSUE THREAD

**Issue by tkeeler33** [fitztrev/shuttle#109]
Currently you have to restart Shuttle whenever you modify .shuttle.json. It'd be nice to have Shuttle auto-refresh the list whenever the file is changed.

**Comment by thshdw** [comment]
@tkeeler33 It should be reading the JSON file again when you click on the icon to load the menu.

On my install this is working. I opened JSON file in an editor > made a change to the JSON file > Went to the menu and my change was reflected. All without closing the app

What version do you have installed? What are you using to edit the shuttle.json file?

**Comment by tkeeler33** [comment]
Interesting, that doesn't happen for me. I'm using version 1.2.2.

For example, when go to the Shuttle menu -> Settings -> Edit and it will open the JSON file with SublimeText. I'll create another entry or category, save and close and when I open the shuttle menu again none of the changes will be reflected. If I quit Shuttle and re-open it the changes will be reflected.

Any thoughts for troubleshooting?

**Comment by tkeeler33** [comment]
Ahh, okay I figured out the problem.

I was storing .shuttle.json on Dropbox with a symlink to ~/.shuttle.json. Switching it to a hard link, although not ideal, did the trick.

**Comment by tkeeler33** [comment]
Just an update - Dropbox won't detect file changes with hard links, so hard linking isn't really a solution.

I'll open up a new request asking for symlink support.

**Comment by thshdw** [comment]
@tkeeler33 Thanks for the update. Perhaps shuttle should have path setting in the shuttle.json file. If the path setting is omitted it assumes that the file is in its default location ~/.shuttle.json. If you have something in this path setting it gets the path from this location.. Thoughts?

**Comment by tkeeler33** [comment]
@thshdw - that would work too. I have added that in a new request - #110
