### ISSUE TITLE
Support for symlinks or custom paths

### ISSUE THREAD

**Issue by tkeeler33** [fitztrev/shuttle#110]
As noted in #109, if you create a symlink to .shuttle.json Shuttle won't refresh settings until the application is relaunched.

Can support for symlinks be added? This is useful to those who use Shuttle on multiple computers and want to store their configuration centrally.

As an alternative solution suggested by @thshdw, changing the path to .shuttle.json would also work.

Thanks!

**Comment by thshdw** [comment]
@tkeeler33 Thanks! I'd prefer the path option in the config file. It would work something like this... 

If the path setting is omitted it assumes that the file is in its default location ~/.shuttle.json. If you have something in this path setting it gets the path from this location.

What does everyone think about this approach?

**Comment by fitztrev** [comment]
@thshdw Sounds good. Seems like a good way to support config storage in Dropbox (see #93)

**Comment by thshdw** [comment]
@tkeeler33 @fitztrev I saw https://github.com/fitztrev/shuttle/pull/93 but what if the user is on OneDrive or some other sharing service. In changes from pull request https://github.com/fitztrev/shuttle/pull/111 if set a path in a ~/.shuttle.path shuttle will read the this file and get the hard coded path. This way its compatible with all sharing services.

**Comment by tkeeler33** [comment]
@thshdw - agreed. The solution should be platform/path agnostic. Nice work in #111

**Comment by thshdw** [comment]
@tkeeler33 Thank you!

**Comment by thshdw** [comment]
@tkeeler33 Custom paths are in the current binary... see the [releases page](https://github.com/fitztrev/shuttle/releases/tag/v1.2.3)

**Comment by tkeeler33** [comment]
Thank you!

**Comment by moll** [comment]
Hey, I'm seeing the same problem in v1.2.6: changes in a symlinked `~/.shuttle.json` don't get picked up until the app is restarted. Was this meant to be fixed? The `~/.shuttle.path` approach seems a slightly weird hack.

**Comment by thshdw** [comment]
@moll The original request was for Symlinks support or Custom Paths. The resolution provided was Custom Paths by setting the alternate location to the JSON file in ```~/.shuttle.path``` 

I think that this adequately solves the issue and lets users modify the path to the location of their choosing. For users that don't want to mess with symbolic links its a nice solution.

However shuttle should probably have symbolic link support. The Unix/Linux way to do this is with symbolic links so shuttle should simply just work as expected. 

I'm not a big fan of requests that ask for multiple things so I'll keep this issue closed and open a new issue on your behalf. 

Thanks!
