### ISSUE TITLE
Escaping spaces and parenthesis does not work

### ISSUE THREAD

**Issue by nofont** [fitztrev/shuttle#112]
Here is how to recreate the issue:

	“Foobar Localhost": [
		{
			"name": "Dev directory",
			"cmd": "cd Dropbox (Personal)/foo/bar"
		}
	]

The above works in Shuttle conf, but the Terminal throws: 

	-bash: syntax error near unexpected token `('

If I try to escape the space and the parentheses like:

	"cmd": "cd Dropbox\ \(Personal\)/foo/bar"

but then Shuttle gives me “error parsing config” which is a bit strange since escaping \n and such works. It’s only when I try to escape spaces and ( or ) that the error occurs.

**Comment by fitztrev** [comment]
I know it's not ideal but this works for now.

```bash
"cmd": "cd Dropbox\\\\ \\\\(Personal\\\\)/foo/bar"
```

Also, zsh appears to be a little more forgiving than bash (for example, not having to escape the parentheses).

**Comment by nofont** [comment]
Maybe not ideal but it works just fine :-)
