### ISSUE TITLE
Yosemite 10.10.3 (14D105g): does not work

### ISSUE THREAD

**Issue by monolithed** [fitztrev/shuttle#114]
It seems after today's update 

![1426793766969](https://cloud.githubusercontent.com/assets/803674/6739234/8576c3b2-ce88-11e4-866a-a33af4c22cda.png)

![1426793780727](https://cloud.githubusercontent.com/assets/803674/6739241/8f41ebf6-ce88-11e4-8725-bb4a090c94fa.png)

**Comment by thshdw** [comment]
@monolithed Are you using the release version or are you compiling from master? Know this will allow me to test using the same version. 

Thanks!

**Comment by monolithed** [comment]
I'm using the release version from http://fitztrev.github.io/shuttle/

**Comment by thshdw** [comment]
@monolithed 
I have the public beta (10.10.3) and all is well. 

![screen shot 2015-03-19 at 4 21 40 pm](https://cloud.githubusercontent.com/assets/4992951/6743212/5ce75eea-ce54-11e4-9598-e5fc07d44916.png)

It could be that something is up with your config if you use TextEdit it can sometimes mess up the text encoding. 
in terminal try cp ```~/.shuttle.json .shuttle.json.backup``` then copy the working test config below. 
```nano ~/Desktop/shuttle.json``` paste the below in the nano window then ```cp ~/Desktop/shuttle.json ~/.shuttle.json```
```
{
  "_comments": [
    "Valid terminals include: 'Terminal.app' or 'iTerm'",
    "In the editor value change 'default' to 'nano', 'vi', or another terminal based editor.",
    "Hosts will also be read from your ~/.ssh/config or /etc/ssh_config file, if available",
    "For more information on how to configure, please see http://fitztrev.github.io/shuttle/"
  ],
  "editor": "default",
  "hosts": [
    {
      "cmd": "ssh username@dev.example.com",
      "name": "My Dev Server"
    },
    {
      "Personal": [
        {
          "cmd": "ssh username@blog.example.com",
          "name": "My blog"
        },
        {
          "Spouse": [
            {
              "cmd": "ssh username@blog2.example.com",
              "name": "Her blog"
            }
          ]
        }
      ]
    },
    {
      "Work": [
        {
          "cmd": "ssh username@dev.example.net -p 3000",
          "name": "dev.example.net"
        },
        {
          "cmd": "ssh username@staging.example.net -p 3000",
          "name": "staging.example.net"
        },
        {
          "cmd": "ssh username@example.net -p 3000",
          "name": "production.example.net"
        }
      ]
    },
    {
      "Vagrant": [
        {
          "cmd": "ssh vagrant@127.0.0.1 -p 2222 -i ~/.vagrant.d/insecure_private_key",
          "name": "precise32"
        }
      ]
    }
  ],
  "launch_at_login": false,
  "show_ssh_config_hosts": true,
  "ssh_config_ignore_hosts": [
  ],
  "ssh_config_ignore_keywords": [
  ],
  "terminal": "Terminal.app"
}
```

**Comment by monolithed** [comment]
The problem was solved by reinstalling

**Comment by thshdw** [comment]
@monolithed Thanks for the update!
