### ISSUE TITLE
Сonnection not occuring if json have blackslash

### ISSUE THREAD

**Issue by indapublic** [fitztrev/shuttle#115]
I have this config

```
{
	"name": "local.vagrant",
	"cmd": "ssh vagrant@192.168.77.100 -i /Volumes/Data/Virtual\\ Machines/Vagrant/.vagrant/machines/default/parallels/private_key"
}
```

Shuttle parsing it correctly. But there is no reaction if I click menu item "local.vagrant"

**Comment by thshdw** [comment]
Hi @indapublic, This is because your path has a space. See https://github.com/fitztrev/shuttle/issues/86, you want to escape your space using 4qty `\\\\` like this:

`/Data/Virtual\\\\ Machines/Vagrant/`

Let us know if that works for you!

**Comment by indapublic** [comment]
@thshdw, yes, it works! Thank you very much

**Comment by thshdw** [comment]
@indapublic You're Welcome! :smile:
