### ISSUE TITLE
Customize the sorting of menu items

### ISSUE THREAD

**Issue by cvdwl** [fitztrev/shuttle#117]
Love the application, especially with the new ssh config option.  Would it be possible to retain the sort order of the ssh_config entries?

**Comment by thshdw** [comment]
@cvdwl as in you want to the order to be exactly the order in your JSON File?

**Comment by thshdw** [comment]
I'll look at this part of the code to see if its feasible.

**Comment by jthoel** [comment]
Any change or plan to integrate this feature?

**Comment by thshdw** [comment]
Hi @jthoel I want to integrate this feature... I just have not had the time to look into it. It's been requested several times so I keep the ticket open. Sorry I can't provide anytime timelines for you. Its on my todo list though 😄

**Comment by thshdw** [comment]
I'm not sure this is going to be possible. It seems like an easy thing but would require some rewriting of code and the shuttle.json syntax would change. 

see http://json.org
*An object is an unordered set of name/value pairs*
*An array is an ordered collection of values*

The JSON syntax is by object not array this is parsed through NSDictionary
https://developer.apple.com/reference/foundation/nsdictionary/1410799-description
*If each key in the dictionary is an NSString object, the entries are listed in ascending order by key, otherwise the order in which the entries are listed is undefined.*

So it seems to do this correctly the code would need to be modified and then the json syntax would need to be changed.  
See also here:
http://stackoverflow.com/questions/10800285/why-does-json-values-get-sorted-alphabetically-ios

**Comment by thshdw** [comment]
As a hack I guess we could add numbers or some sorting sequence and then chop these off as they are added to the menu. 

```
  "hosts": [
    {
      "cmd": "ps aux | grep defaults",
      "name": "[2]Apple - Opens in Default-window-theme-title"
    },
    {
          "cmd": "ps aux | grep defaults",
      "name": "[1]Work - Opens in Default-window-theme-title"
    },
    {
      "[b]Work Servers": [
        {
          "cmd": "echo '—->WARNING! Running commands<-- Are you sure? y/n'; read sure; if [ $sure == y ]; then echo running command && ps aux | grep [a]pple; else echo save to history and show... && history -s 'ps aux | grep [a]pple' && osascript -e 'tell application \"System Events\" to keystroke \"p\" using {control down}'; fi",
	      "inTerminal": "current",
          "name": "Logs - Opens in the current active terminal window"
        },
        {
          "Jane’s Servers": [
            {
              "cmd": "ssh username@blog2.example.com",
              "inTerminal": "tab",
              "name": "SSH blog - Opens in Tab of active window",
              "theme": "basic",
              "title": "title of tab"
            },
            {
              "cmd": "ssh username@shop1.example.com",
              "inTerminal": "new",
              "name": "SSH Shop - Opens in New Window",
              "theme": "basic",
              "title": "title of new window"
            }
          ]
        }
      ]
    },
    {
      "[a]Zoo": [
        {
          "cmd": "ssh vagrant@127.0.0.1 -p 2222 -i ~/.vagrant.d/insecure_private_key",
          "name": "Vagrant - Opens in default-window-theme-title"
        }
      ]
    }
  ]
```

**Comment by thshdw** [comment]
Anyone have any comments?

**Comment by fooman** [comment]
@thshdw how about adding a new optional key "sort_order"?

```
  "hosts": [
    {
      "cmd": "ps aux | grep defaults",
      "name": "Apple - Opens in Default-window-theme-title",
      "sort_order": 2
    },
    {
      "cmd": "ps aux | grep defaults",
      "name": "Work - Opens in Default-window-theme-title",
      "sort_order": 1
    }
```

**Comment by hessijames79** [comment]
I would also like to be able to sort manually.

**Comment by mbitson** [comment]
I would also like this functionality. I came to suggest the same thing as @fooman - I think that assuming a default sort_order of 0 and then allowing users to specify new sort orders (positive or negative) would be able to accomplish everything needed without modifying the current JSON syntax.

👍

**Comment by thshdw** [comment]
Added in https://github.com/fitztrev/shuttle/pull/234
