### ISSUE TITLE
ssh_config alias handling

### ISSUE THREAD

**Issue by cvdwl** [fitztrev/shuttle#118]
When I have a line in my ssh config:

>Host foo bar

Which is essentially an aliasing allowing either "ssh foo" or "ssh bar" to work.  The resulting call to the terminal is:

>ssh foo bar

which attempts to execute the command "bar" on the host *foo*.

**Comment by thshdw** [comment]
I'll do some testing and get back with you :smile:

**Comment by keesfransen** [comment]
Hi, I have patched this in pull #154. 

We have an issue where our SFTP client Transmit.app will not allow the `/` character in a hostname and we use the slashes in our shuttle config to generate the submenus and in `ssh` for host inheritance

Hope this helps,
Cheers,
Kees

**Comment by thshdw** [comment]
Thanks! This looks good. I'll merge it and do some testing before the next release.

**Comment by keesfransen** [comment]
Awesome! :grinning:

**Comment by thshdw** [comment]
Closed... this is in v1.2.6 see #154
