### ISSUE TITLE
Icon doesn't turn white when menu is opened

### ISSUE THREAD

**Issue by FezVrasta** [fitztrev/shuttle#120]
Usually icons turn white when opened:

![image](https://cloud.githubusercontent.com/assets/5382443/7901990/9f34439c-07a4-11e5-8bb3-506035638c34.png)

But this app doesn't work in this way:

![image](https://cloud.githubusercontent.com/assets/5382443/7901992/b202e8f2-07a4-11e5-8105-d651105d72bf.png)

Could you fix it? I know that is a stupid detail but it feels just wrong.

**Comment by thshdw** [comment]
You are correct. It should be an easy enough change! Added to the roadmap :smile:

**Comment by thshdw** [comment]
Complete. Release [v1.2.4.](https://github.com/fitztrev/shuttle/releases/tag/1.2.4)
