### ISSUE TITLE
Why limit this to SSH only?

### ISSUE THREAD

**Issue by FezVrasta** [fitztrev/shuttle#122]
I use this applet to run any kind of bash command so I was wondering why you promote it as an SSH launcher and not a generic bash launcher.

**Comment by thshdw** [comment]
Shuttle was inspired by [SSHMenu](http://sshmenu.sourceforge.net/) which is a Linux app that does something similar. Perhaps when features that allow you to launch commands in existing terminal windows (see #104) hit master; we can advertise this more. :smile
