### ISSUE TITLE
Menu items are duplicated

### ISSUE THREAD

**Issue by monolithed** [fitztrev/shuttle#125]
![img-2015-08-24-12-59-13](https://cloud.githubusercontent.com/assets/803674/9437583/0677fbd6-4a60-11e5-9da0-8380dd0aa04f.png)

**Comment by thshdw** [comment]
@monolithed Could you test to see if you have the issue in the [latest release?](https://github.com/fitztrev/shuttle/releases/tag/v1.2.3)

**Comment by monolithed** [comment]
@thshdw, I see the same problem

**Comment by thshdw** [comment]
Would you be able to share your config with me? My email address is on my git home page. 

Could it be possible that you have ```"win"``` in your ssh config ?

**Comment by monolithed** [comment]
@thshdw, please check your email

**Comment by thshdw** [comment]
Thanks!

**Comment by thshdw** [comment]
In your ssh config you have ```Host win``` what if you changed this to ```Host win-in-config``` do you still get duplicate names in the menu?

**Comment by thshdw** [comment]
When I load you JSON conifg this is what I see:
![screen shot 2015-10-16 at 9 35 09 am](https://cloud.githubusercontent.com/assets/4992951/10547423/4b33c09a-73e9-11e5-9451-14e270152075.png)

I think the duplicate name is coming from your ssh config
if you don't want shuttle to load the config set this in your JSON config.
``` 
"show_ssh_config_hosts": true,
```

**Comment by monolithed** [comment]
> I think the duplicate name is coming from your ssh config

It seems true


> "show_ssh_config_hosts": false,

I got it, thanks!
