### ISSUE TITLE
Terminal tab name

### ISSUE THREAD

**Issue by greyhard** [fitztrev/shuttle#126]
When i open a ssh via Shuttle i see a "SSH" in terminal tab
On double click i can change a terminal tab name
how i can add a name for terminal tab in a shuttle config ?
{
"tabname": "GT-Shop", 
"name": "GT-Shop",
"cmd": "ssh root@95.85.20.59"
},

**Comment by nathanpitman** [comment]
+1

**Comment by thshdw** [comment]
Hello, I'm working on getting this into master. See #102

**Comment by thshdw** [comment]
Added Terminal title and theme changes to master For a list of changes see #128

**Comment by fluidsonic** [comment]
This doesn't really work.

Shuttle does set the *window title* when it opens Terminal instead of setting the *tab title*.
The window title is overwritten by the remote server shortly after, making the title property effectively useless.

Is there any way to set the **tab title**?

**Comment by thshdw** [comment]
@fluidsonic when you say that its not working... is that in the context of iTerm Stable or Nightly?

**Comment by fluidsonic** [comment]
@thshdw it's the standard Mac Terminal app on El Capitan.

**Comment by thshdw** [comment]
@fluidsonic thanks for the update... Now I can investigate :smile:

**Comment by thshdw** [comment]
@fluidsonic Here is my test JSON.
```
{
  "editor": "default",
  "launch_at_login": false,
  "terminal": "Terminal.app",
  "iTerm_version": "stable",
  "default_theme": "Default",
  "open_in": "tab",
  "show_ssh_config_hosts": false,
  "ssh_config_ignore_hosts": [  ],
  "ssh_config_ignore_keywords": [  ],
  "hosts": [
    {
      "cmd": "ssh my server@localhost",
      "theme": "Homebrew",
      "title": "name one",
      "inTerminal": "tab",
      "name": "Opens in new tab1"
    },
    {
      "cmd": "ps aux | grep defaults",
      "theme": "Homebrew",
      "title": "name two",
      "inTerminal": "tab",
      "name": "Grep - Opens in new tab2"
    }
  ]
}
```

When I run ``` "name": "Opens in new tab1"``` I get a window with my title. As Expected. 
When I run ``` "name": "Grep - Opens in new tab2"``` the command opens in the new tab and I get the name as expected. Now I ssh to a server in this window my name stays but its hyphenated with the command after. 

If I click on tab1 the window title changes to the the same as tab1 and if click on tab2 the window title changes. 

<img width="450" alt="screen shot 2016-01-15 at 7 47 52 pm" src="https://cloud.githubusercontent.com/assets/4992951/12370059/663324d8-bbc1-11e5-9553-1c5504d234df.png">

Are you not getting the same thing?

**Comment by fluidsonic** [comment]
It is the **window title** which is set, not the **tab title**.

If you set the **tab title** using the tab inspector then terminal wouldn't show the command at all.
The **window title** is shown for me but as soon as I completed the SSH login the server overwrites the window title with the host name. In your case you just have luck that the server doesn't touch the session's window title.

Refer to Terminal's tab inspector:
![screenshot 2016-01-18 10 09 34](https://cloud.githubusercontent.com/assets/85242/12387360/393f6ab0-bdcc-11e5-9e5f-3711e6847608.png)
Shuttle sets the window title (which can be changed by the server) while I expect it to set the tab title.

**Comment by thshdw** [comment]
@fluidsonic I did some quick testing and it seems if you don't pass a theme the title does not get set. As a test in your command add ```"theme": "basic"```

or add the below
```
  {
      "title": "foo",
      "cmd": "ps aux | grep [d]efaults",
      "name": "Name Test",
      "theme": "basic"
    },
```

**Comment by fluidsonic** [comment]
Same problem.

Try this example:
```json
{
  "name":  "Title Test",
  "cmd":   "sleep 0.5 && echo -n -e '\\033]0;TITLE OVERWRITTEN\\007'",
  "title": "Title Test",
  "theme": "basic"
}
```

The window title gets overwritten by the command.
The same happens when you connect to a server through SSH and the server subsequently uses this approach to change the window title.

**Comment by thshdw** [comment]
Hello, 
the command ```"echo -n -e '\\033]0;MyTitle\\007'"``` the \\\033 0; \\\007 bits specifically overwrite the title. Using this command your title will always be overwritten

I think a better example would be:
```"cmd":   "sleep 0.5 && ssh me@example.com",```
when I do this on my ssh server my title remains And what I see in the tab and in the window is something like this:
thshdw -- myTitle -- ssh me@example.com

Now you can limit this by going to terminal > preferences > profiles select your profile and then press window and un-check active process name. Click on Tab and Uncheck Working direcotory or document and uncheck Active Process name

**Comment by fluidsonic** [comment]
The `echo` command is just an example!
The remote server *can* use the very same approach to change the terminal's window title. This is what's happening for me all the time when connecting to Ubuntu instances on Amazon Web Services.
Removing path and process through Preferences doesn't change that behavior.

My point is that Shuttle sets the **window title** which the remote server can easily overwrite and in many cases does. Instead I'd like it to set the **tab title (!)** which can not be overwritten by the remove server.

The `echo` command is a simple way to test this issue.

**Comment by thshdw** [comment]
@fluidsonic 
Thanks!

Here is what the applescript is doing.

```
set custom title of selected tab of front window to theTitle
```

**Comment by thshdw** [comment]
Here is the applescript dictionary for Terminal....

```
tab n : A tab.
elements
contained by windows.
properties
number of rows (integer) : The number of rows displayed in the tab.
number of columns (integer) : The number of columns displayed in the tab.
contents (text, r/o) : The currently visible contents of the tab.
history (text, r/o) : The contents of the entire scrolling buffer of the tab.
busy (boolean, r/o) : Whether the tab is busy running a process.
processes (list of text, r/o) : The processes currently running in the tab.
selected (boolean) : Whether the tab is selected.
title displays custom title (boolean) : Whether the title contains a custom title.
custom title (text) : The tab’s custom title.
tty (text, r/o) : The tab’s TTY device.
current settings (settings set) : The set of settings which control the tab’s behavior and appearance.
cursor color (color) : The cursor color for the tab.
Deprecated; use current settings instead.
background color (color) : The background color for the tab.
Deprecated; use current settings instead.
normal text color (color) : The normal text color for the tab.
Deprecated; use current settings instead.
bold text color (color) : The bold text color for the tab.
Deprecated; use current settings instead.
clean commands (list of text) : The processes which will be ignored when checking whether a tab can be closed without showing a prompt.
Deprecated; use current settings instead.
title displays device name (boolean) : Whether the title contains the device name.
Deprecated; use current settings instead.
title displays shell path (boolean) : Whether the title contains the shell path.
Deprecated; use current settings instead.
title displays window size (boolean) : Whether the title contains the tab’s size, in rows and columns.
Deprecated; use current settings instead.
title displays file name (boolean) : Whether the title contains the file name.
Deprecated; use current settings instead.
font name (text) : The name of the font used to display the tab’s contents.
Deprecated; use current settings instead.
font size (integer) : The size of the font used to display the tab’s contents.
Deprecated; use current settings instead.
font antialiasing (boolean) : Whether the font used to display the tab’s contents is antialiased.
Deprecated; use current settings instead.
```

According to the dictionary 
```set custom title of selected tab of front window to theTitle```
is the correct way to set the tab.

I guess we could do some funky hack to inject the zterm way of changing the title but I'm going to frown on it. 

Comments welcome

**Comment by fluidsonic** [comment]
Unfortunately there seems to be no way to set the *Tab Title* with AppleScript or through a terminal command :(
Using `custom title` you can only set the *Window Title*.

I also found no way to prevent a remote server from overwriting the *Window Title* which would've been an alternative.

Anyone else an idea?

**Comment by thshdw** [comment]
@fluidsonic 
I think I found something that will work for you... 

edit ```/etc/bashrc``` add the following:

```
function tabname {  
          printf "\e]1;$1\a"  
     }  
```
in your JSON change your ```cmd``` to the following:
```  "cmd":   "tabname FOO; ssh user@myServer.Example.com",```

_Thanks to user [Topher Kessler](https://discussions.apple.com/thread/4116582?start=0&tstart=0) at the apple discussions forum_

**Comment by fluidsonic** [comment]
Yes and no!

It indeed sets the *Tab Title* instead of the *Window Title* - nice one!
Unfortunately the *Tab Title* resets to an empty string as soon as the SSH sign-in completes :(

Looks like I have to give up the idea of having a useful title in the Terminal tab.

**Comment by thshdw** [comment]
@fluidsonic
Are you using passwords to login to your ssh server? Or to you have ssh keys setup? When I ssh to my server using ssh keys title ```FOO``` remains

**Comment by thshdw** [comment]
@fluidsonic 
I have confirmed that when using ssh keys the title that set with tabname remains but when ssh'ing to a system using password login the title is overwritten. There may not be a way around this.

**Comment by fluidsonic** [comment]
@thshdw Thanks for checking again. I agree that there is likely no way to prevent that behavior in Terminal :(

**Comment by thshdw** [comment]
@fluidsonic You're Welcome!
