### ISSUE TITLE
Shuttle doesn't open iTerm 2.9 (nightly)

### ISSUE THREAD

**Issue by Labutin** [fitztrev/shuttle#127]
Shuttle ( http://fitztrev.github.io/shuttle/ ) doesn't open iTerm 2.9 (nightly).
And all works fine with iTerm 2.1

I have set:
"terminal": "iTerm"

**Comment by gnachman** [comment]
Applescript support has changed in 2.9 and is not backward compatible. The docs are here: https://iterm2.com/applescript.html

Should be a relatively easy change.

**Comment by FezVrasta** [comment]
+1 for a new version of shuttle compatible with 2.9/3

**Comment by thshdw** [comment]
Hello All, 
On my G+ page I had a [poll](https://plus.google.com/+MattTurner-ThShdwKnws/posts/akgb9gwrj8J) regarding this topic. I think it's best that sshuttle support all three versions of iTerm. I plan on supporting this by implementing a settings database. This database will contain the applescript needed for all three versions. You would select the desired version in a settings dialog. Until I can get this coded I'll build a version that works with Nightly. Feel free to contact me if you have questions. -Matt

**Comment by thshdw** [comment]
Complete! See release [v1.2.3](https://github.com/fitztrev/shuttle/releases/tag/v1.2.3)

**Comment by FezVrasta** [comment]
Thank you!!
