### ISSUE TITLE
Shuttle --> About wont show on monitor 2 if your in full screen mode

### ISSUE THREAD

**Issue by thshdw** [fitztrev/shuttle#130]
When clicking on the about dialog from the apple menu in monitor 2, the window opens in monitor 1. This only happens if you have a full screen app open on monitor 2

**Comment by thshdw** [comment]
@dcinzona Do you know if its possible to display a window on the top of a full screen window?

If I click on shuttle > about from monitor 2's apple menu and I happen to have another app in fullscreen mode on monitor 2 then the shuttle's about dialog displays on monitor 1. 

If both monitors don't have full screen apps then shuttle > about opens in the monitor of the apple menu as expected.

**Comment by dcinzona** [comment]
My guess here is that this is by design.  When an application is full screen, it is the only application on that screen / desktop.  Because Shuttle would be a separate application, I think it would have to appear on a desktop / screen that is not already...

**Comment by thshdw** [comment]
Thanks for taking a look :+1:
