### ISSUE TITLE
shuttle does not work when doing actions in .bash_profile

### ISSUE THREAD

**Issue by fabriziopandini** [fitztrev/shuttle#133]
Hi
After setting env variables for docker machine with eval "$(docker-machine env default)" in my .bash_profile shutte does not work anymore...
It seems that every command in .bash_profile is executed after ssh command issued by shuttle, and thus it does not work.
Is it possible to execute ssh after loading .bash_profile?
Thanks

**Comment by thshdw** [comment]
Hi! It's hard to say as I'm not sure what your trying to accomplish. Maybe you want to put the ```.bash_profile``` stuff that is not working in ```.bashrc```

.bash_profile is for Login shells
.bashrc is for Interactive shells

**Comment by thshdw** [comment]
Closing this for now. Please reopen if you have questions.
