### ISSUE TITLE
Terminal.app tabs or windows always open with OSX "Basic" theme

### ISSUE THREAD

**Issue by primary0** [fitztrev/shuttle#138]
On a fresh El Capitan install all the Terminal.app windows and tabs always start with the "Basic" theme when launching from Shuttle; even when the default is set to another one. Is it possible to assign a Terminal.app theme from Shuttle?

**Comment by thshdw** [comment]
Hi @primary0 this is due to the recent changes in the applescript. The new changes allow you to set  the theme per command. In your command set:
```
"theme": "Homebrew"
``` 
This would set the theme to Homebrew.

Currently if a theme is not passed the applescript wont run. To get around this problem if a theme is not set, in code I force the theme to ```basic```.
 
You bring up a valid point... Not everyone keeps the default theme ```basic``` So either I figure out a way to get the default theme and pass that or we have a new Global setting where you manually set the theme for all windows.

**Comment by primary0** [comment]
Thanks! That fixes the problem. I think it would be nice to have a global theme setting.

**Comment by thshdw** [comment]
You're welcome! 

Agreed. You should have the ability to set this globally. Re-opening and turning this into an in-progress enhancement.

**Comment by Dreeg** [comment]
Hi all, this temporary workaround ("theme": "Pro",) don't work for me..
It continues to open up new tabs with the theme Basic..

**Comment by primary0** [comment]
@Dreeg This is how it worked for me
```
"MyApp": [
{
  "theme": "Pro",					
  "name": "My App",
  "cmd": "ssh user@example.com",							
},
```

**Comment by primary0** [comment]
@Dreeg correct. Global setting feature is in-progress as @thshdw said.

**Comment by Pingedsole** [comment]
Hi,  Can you advise specifically where I put "theme": "Homebrew" in the shuttle.json file?

**Comment by Pingedsole** [comment]
found it :-)

**Comment by primary0** [comment]
@Pingedsole this worked for me:

```
"Web Servers": [
{
  "theme": "Pro",					
  "name": "Web Server 1",
  "cmd": "ssh user@example.com",							
},
```

**Comment by Pingedsole** [comment]
Hi,

So I have a good few sections which worked fine before I started messing around adding the theme.  

Do I need to add the theme entry to every section as currently when I make a change I get Error parsing config.

{
	"_comment1": "Valid terminals include: 'Terminal.app' or 'iTerm'",
	"_comment2": "Hosts will also be read from your ~/.ssh/config or /etc/ssh_config file, if available",
	"_comment3": "For more information on how to configure, please see http://fitztrev.github.io/shuttle/",
	"terminal": "Terminal.app",
	"launch_at_login": true,
	"hosts": [
		
		{
			"theme": "Homebrew”,
			"name": "🔌 SERIAL PORT 🔌",
			"cmd": "sudo cu -l /dev/cu.usbserial  -s 9600"
	
		},
		{
			"📡 Connection 1📡": [
				{
					"theme": "Homebrew”,
					"name": "Connection1a",					
					"cmd": "ssh random1.address.com"
				},
				{
					"theme": "Homebrew”,
					"name": "Connection1b",
					"cmd": "ssh random2.address.com"
				},
{
			"💻 Connection2💻": [
				{
					""theme": "Homebrew”,
					name": "Connection2a,
					"cmd": "random2a.address.com"
				},
				{
					"theme": "Homebrew”,
					"name": "Connection2b",
					"cmd": "random2b.address.com"
				},

**Comment by primary0** [comment]
@Pingedsole check your syntax again.

```
""theme": "Homebrew”,
name": "Connection2a,
"cmd": "random2a.address.com"
```
Repeated quotes near "theme" and a missing quote before "name".

**Comment by Pingedsole** [comment]
Yep, that is a red herring, apologies for the syntax error.

Let's just look at the following\:

{
			"name": "🔌 SERIAL-PORT 🔌",
			"cmd": "sudo cu -l /dev/cu.usbserial  -s 9600"
	
		},

This is fine but as soon as I add the theme I get an error:

{
			"theme":  "Homebrew”,
                        "name": "🔌 SERIAL-PORT 🔌",
			"cmd": "sudo cu -l /dev/cu.usbserial  -s 9600"
	
		},

**Comment by thshdw** [comment]
Hello @Pingedsole the error you get is parsing the config? This is working for me... 

```
        {
          "cmd": "sudo cu -l /dev/cu.usbserial -s 9600",
          "theme": "Homebrew",
          "name": "Serial-Port"
        },
```

**Comment by Pingedsole** [comment]
Hi,

This worked.  The only hing that was different was that the theme was 
referenced last.

Anyway, all working and thanks for the quick replies everyone.

On 26/10/2015 19:29, Matt Turner wrote:
>
> Hello @Pingedsole <https://github.com/Pingedsole> the error you get is 
> parsing the config? This is working for me...
>
> |{ "cmd": "sudo cu -l /dev/cu.usbserial -s 9600", "theme": "Homebrew", 
> "name": "Serial-Port" }, |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/fitztrev/shuttle/issues/138#issuecomment-151258077>.
>

-- 
Rgds
Steve Miller

**Comment by thshdw** [comment]
@Pingedsole You're welcome and thanks for the update!

**Comment by danherd** [comment]
Am I right in thinking you cannot customise the theme for SSH config hosts yet?

**Comment by Pingedsole** [comment]
I have it all working as required.

**Comment by thshdw** [comment]
@danherd Soon v1.2.5 will be released and this version will have a global theme setting. Currently if you don't set a theme, theme basic (OS X) and theme Default (iTerm) will be passed. As of now you can only set a theme per command. If you use iTerm make sure that you use the same case. ```default``` and ```Default``` are different. 
 
```
        {
          "cmd": "sudo cu -l /dev/cu.usbserial -s 9600",
          "theme": "Homebrew",
          "name": "Serial-Port"
        },
``` 

The above will pass theme ```Homebrew```

**Comment by thshdw** [comment]
Hi @primary0 and @danherd Global theme settings are now in v1.2.5 see the releases page and the readme.md for the new syntax. Thanks!

**Comment by Dreeg** [comment]
Hi @thshdw, How I can update Shuttle without lose configuration?

**Comment by thshdw** [comment]
@Dreeg The new releases won't delete your configuration file. If you have a ```~/.shuttle.json``` file; shuttle will use it. However your old config wont have some of the new directives so you will have to add those in manually. Let me know if you need help and check out the readme.md for a full list of directives. :smile:

**Comment by primary0** [comment]
@thshdw nice! Thanks.

**Comment by thshdw** [comment]
You're Welcome! :smiley:
