### ISSUE TITLE
Sync the config.json

### ISSUE THREAD

**Issue by vicmosin** [fitztrev/shuttle#139]
Is it somehow possible to sync settings file via Dropbox for example? Or at least to change the shuttle's default settings file path so the app will look for it at cloud storage's app folder?

**Comment by thshdw** [comment]
Hi @vicmosin this feature is in the current build. 
On your system create a file called shuttle.path this file should be in home folders dir
```
~/.shuttle.path
```
In this file is the path to the JSON settings. Mine currently reads /Users/thshdw/Desktop/shuttle.json

**Comment by vicmosin** [comment]
Perfect, thanks!

**Comment by thshdw** [comment]
You're Welcome!
