### ISSUE TITLE
shuttle does not use change default profile with iterm2

### ISSUE THREAD

**Issue by alexandnpu** [fitztrev/shuttle#142]
I installed iterm2, then shuttle.

Happy to use them.

Recently I changed iterm2 default profile to solaried theme.
But when I open new terminal window with shuttle.
It still uses the original black profile, not my solarized one.

**Comment by thshdw** [comment]
Hi @alexandnpu v1.2.5 now has an option to set the default theme. Make sure that your Profile ```solarized``` is the same spelling and syntax as you see in your iTerm preferences. iTerm themes are case sensitive. See the changes in readme.md for all the new options. Thanks!

**Comment by thshdw** [comment]
@alexandnpu did you get this sorted out? Let me know if you need assistance.

**Comment by alexandnpu** [comment]
@thshdw , after installing the v1.2.5, my problem solved. Thx.

**Comment by thshdw** [comment]
Thanks for the update! :)
