### ISSUE TITLE
Not working on El Capitan with iTerm

### ISSUE THREAD

**Issue by indapublic** [fitztrev/shuttle#144]
Hello! First, thank you for your great utility!
I have a trouble after installing fresh El Capitan.

El Capitan 10.11.1
iTerm Build 2.9.20151001
"terminal": "iTerm"

There is no reaction while I clicking on any shortcut in Shuttle Menu.
If I use "Terminal.app" instead of "iTerm" in Shuttle config - all working fine.
What a reason?
Thank you in advance

**Comment by thshdw** [comment]
@indapublic In your shuttle.json file make sure you have setting 

```
"iTerm_version": "VALUE",
```
Where VALUE can be ```"stable"``` or ```"nightly"```

**Comment by indapublic** [comment]
Thanks for repsonse.
Yeah, it was missed. But "iTerm_version" is not helps. "stable" or "nightly" - no difference.

**Comment by thshdw** [comment]
@indapublic Are you using the most recent version of shuttle? Only iTerm stable and nightly and OS X terminal are supported.

**Comment by indapublic** [comment]
@thshdw I'm using 1.2.4. I will try update to 1.2.5 right now

**Comment by indapublic** [comment]
@thshdw Yep! It working with 1.2.5. Thank you very much for help.

**Comment by thshdw** [comment]
You're Welcome! Thanks for the update!
