### ISSUE TITLE
Error parsing config

### ISSUE THREAD

**Issue by borsn** [fitztrev/shuttle#145]
I deleted the menus from the default configuration. And only left the one below, cause I only have one server I need to SSH to atm.

`"hosts": [   
{
      "name": “name“,
      "cmd": "ssh user@myserverip"
    }
]`

And now I get **Error parsing config**.

Actually, in the *default config* even just changing the name of one of the values resulted in the same error.

How do I fix this? Thanks.

**Comment by thshdw** [comment]
Hi @borsn it could be due to your italicized quotes ```“``` which are different from ```"``` and could cause the parsing error.

here is a working config with the bare minimum

```
{
  "editor": "default",
  "launch_at_login": false,
  "terminal": "iTerm",
  "iTerm_version": "nightly",
  "default_theme": "Default",
  "open_in": "tab",  
  "show_ssh_config_hosts": false,
  "ssh_config_ignore_hosts": [  ],
  "ssh_config_ignore_keywords": [  ],
  "hosts": [
    {
      "cmd": "ps aux | grep defaults",
      "name": "Grep - Opens in Default-window-theme-title"
    }
  ]
}
```

**Comment by thshdw** [comment]
@borsn ...Actually the bare minimum would be this :smile: 

```
{
  "editor": "default",
  "terminal": "iTerm",
  "iTerm_version": "nightly",
  "default_theme": "Default",
  "open_in": "tab",  
  "hosts": [
    {
      "cmd": "ps aux | grep defaults",
      "name": "Grep - Opens in Default-window-theme-title"
    }
  ]
}
```

**Comment by thshdw** [comment]
The above is what I would consider a safe minimum config. I'm nitpicking here but if you wanted the config to be even smaller you could use osx terminal, and cut out everything else. that would look like this 
```
{
  "terminal": "Terminal.app",
  "hosts": [
    {
      "cmd": "ps aux | grep defaults",
      "name": "Grep - Opens in Default-window-theme-title"
    }
  ]
}
```
This is not recommended but it will work (only for OSX terminal) if you don't care about all the extra config options.

**Comment by borsn** [comment]
@thshdw Thank you! That worked...I didn't pay much attention to the quotes but guessing it's got something to do with autocorrect.

Um, one more question. How do we change the theme, is there a list of themes available somewhere?

**Comment by thshdw** [comment]
@borsn You're Welcome!

Regarding the theme you have two options:
1. We have a global setting for theme called ```"default_theme": "Dagobah",``` _all windows will get this_
2. We have a command level setting for theme called ```"theme": "Grass",``` _only this command gets this_

The command level setting will over write the default one. This could be useful if you want to set a special theme for a site your sshing too.

Themes in iTerm and OSX Terminal are in preferences and are called Profiles. Profiles in iTerm are case sensitive. 

```
{
  "terminal": "Terminal.app",
  "default_theme": "Homebrew",
  "hosts": [
    {
      "cmd": "ps aux | grep defaults",
      "name": "Grep - Opens in Default-window-theme-title",
      "theme": "Grass"
    }
  ]
}
```

so in the above we are saying all windows get ```Homebrew``` theme except for   ```Grep - Opens in Default-window-theme-title``` which gets theme ```Grass```
