### ISSUE TITLE
how can i input password from config

### ISSUE THREAD

**Issue by z-n** [fitztrev/shuttle#146]
how can i input password from config ,thanks

**Comment by thshdw** [comment]
Hi @z-n There are other threads about this [here](https://github.com/fitztrev/shuttle/issues/8) and [here](https://github.com/fitztrev/shuttle/issues/75). Basically this not recommended as the password is then stored in plain text

If we are talking about ssh you would be better off using ssh public keys. If this is not possible you could mess around with sshpass or expect

But in the end its a bad security practice and discouraged. Hope this helps :smile:

**Comment by z-n** [comment]
3Q

**Comment by thshdw** [comment]
You're Welcome!
