### ISSUE TITLE
Shuttle open two ITerm windows in "nightly" mode if ITerm was not opened before

### ISSUE THREAD

**Issue by indapublic** [fitztrev/shuttle#147]
Hello. Thanks again for awesome utility!

My config's part:
```
"terminal": "iTerm",
"iTerm_version": "stable",
"default_theme": "Transparent Screen 2"
```

All working successfully. But I change "iTerm_version" to "nightly", Shuttle create two new ITerm window if ITerm was not running before. Why?

**Comment by thshdw** [comment]
@indapublic You're Welcome! We are happy you find it useful. 

Do you have both stable and nightly installed? If so try the following:

* Remove iTerm 2 from applications. Search your system for iTerm maybe the app is in other folders remove all instances of the app. 
* Remove iTerm and iTerm2 from ~/Library/Application Support 
* Remove ~/Library/Preferences/com.googlecode.iterm2.plist
* Download a fresh Nightly https://iterm2.com/downloads/nightly/#/section/home
* Open iTerm one time and go to the preferences area.

Let me know if this works.

**Comment by indapublic** [comment]
Did all points. Now ITerm open and close immediately.
If I trying to run ITerm via Shuttle again - I see this message
https://dl.dropboxusercontent.com/spa/f2flw5cwyoai67g/mkxsa6lz.png

**Comment by thshdw** [comment]
@indapublic Seems that something is wrong in the config. Would you be willing to share your Json config with me? My personal email account is on my github profile. Thanks!

**Comment by indapublic** [comment]
I'm deleting my config and restarted Shuttle - It created default config, I guess. I'm changing "terminal" to "iTerm" - same behaviour.
You can see my config at https://gist.github.com/indapublic/28ac8354d9588283d3b2

**Comment by thshdw** [comment]
@indapublic correct when you delete your config and start shuttle a default one is created. :smile: 
So in that config ```"default_theme": "Homebrew",``` won't be valid for a fresh install of iTerm because it does not exist. I created a ticket for this issue see #143 Perhaps your config is trying to use an iTerm theme that does not exist?

**Comment by thshdw** [comment]
See iTerm preferences then profiles to see the theme names. :smile:

**Comment by indapublic** [comment]
@thshdw But "Transparent Screen 2" was before I'm removing iTerm and all linked data.
I will try to make one test more some later. Thank you

**Comment by thshdw** [comment]
@indapublic Thanks! So the name of your theme was "Transparent Screen 2"?

I have not tested a theme with spaces in the name. That could be the issue. I'll do some testing on my side.

**Comment by indapublic** [comment]
@thshdw Yes, it's my default profile usually (for second monitor)
Now I'm setting "default_theme" to "Default" and creating "TransparentScreen2" (without spaces). Screen is available at https://dl.dropboxusercontent.com/spa/f2flw5cwyoai67g/m_32yr17.png
My config is https://gist.github.com/indapublic/adae4acb65893f35722d
"Default", "TransparentScreen2" and "Transparent Screen 2" have  same behaviour. There is no difference.
iTerm is latest.
(c) "iTerm2 2.9.20151113-nightly is currently the newest version available."

**Comment by thshdw** [comment]
@indapublic I can't duplicate the issue. my iTerm is ```Build 2.9.20151006-nightly``` I'll get the same version you have do some testing. A reminder that in the default json config there are some command level theme settings. these are set to ```basic``` which is a OSX terminal theme.

**Comment by indapublic** [comment]
Ok, let's think this is my individual issue :) I will return to stable iTerm. Thank you very much

**Comment by thshdw** [comment]
I was looking just now at the iTerm change log and there have been some apple script changes. I'll still test the same version you have. If its a bug i'll reopen this!

**Comment by thshdw** [comment]
@indapublic I downloaded ```Build 2.9.20151113-nightly``` interestingly when I ran shuttle iTerm 2.1.4 stable version opened. It turns out that i had a copy of stable in my downloads folder. I searched my mac for iTerm, moved all stable to the trash, then emptied the trash and all was working :smile: .

Because of the differences in applescipts as of now both versions cant exist on the same system. 
In the applescripts for both ```stable``` and ```nightly``` I do this:

```
	tell application "iTerm"
```
so if you have both in your system and it does not matter where on your system then the applescripts wont work as it won't know which iTerm to use. 

Perhaps I can do:
```
	tell application "iTerm2"
```
for the nightly versions.

Reopening to investagate. 

I'll bet you had both nightly and stable on your mac

**Comment by indapublic** [comment]
No, only one ("nightly" at current time)

**Comment by thshdw** [comment]
Thanks!
one other question in your first post you say _"iTerm_version" to "nightly", Shuttle create two new ITerm window if ITerm was not running before."_
I forgot to ask if it closes the first  window automatically or do you end up with two windows?

**Comment by indapublic** [comment]
@thshdw Be honest, I'm not understand your question :(

**Comment by thshdw** [comment]
@indapublic no worries. 
Here is a gif.. 

![iterm-shuttle-first-run](https://cloud.githubusercontent.com/assets/4992951/11162541/618259ca-8a63-11e5-97d4-bd2e86777c2e.gif)

so for you does the first window open then close like in the animated gif?

**Comment by indapublic** [comment]
@thshdw No, I has two opened iTerm windows in my first post. In your case, your first windows closing, I see.

**Comment by thshdw** [comment]
@indapublic Which command from the default config does this?

**Comment by indapublic** [comment]
@thshdw 

```
ssh ec2-user@xxx.xxx.xxx.xxx -i /path/to/my/key
```

**Comment by indapublic** [comment]
@thshdw Now I'm returning to stable iTerm and default Shuttle config, same behaviour. Wait a minute, I will post my info

**Comment by thshdw** [comment]
@indapublic are you on gitter... we can chat there to sort this out if you like

**Comment by indapublic** [comment]
@thshdw Never used it before, but it's okay.

**Comment by thshdw** [comment]
This ended up being a theme issue. If you are using multiple themes or you want one theme for all windows you have to let shuttle manage the themes. 
In iTerm sent the default profile to ```Default``` In your shuttle .json set the default theme or set the theme per command.
