### ISSUE TITLE
Cache config in ram?

### ISSUE THREAD

**Issue by FezVrasta** [fitztrev/shuttle#149]
Not sure if this is the reason, but most of the times, when I click on shuttle, the loading icon appears for few seconds and then the menu is open.

I think this happens because the app is fetching the config from the configuration file.

I've an iMac 5k with fusion drive, so I think it have decent performances... Maybe you could always cache the configuration in RAM and update it after the menu has been open?

**Comment by thshdw** [comment]
Hello @FezVrasta I don't see this issue as I have an ssd drive but I'm aware it exists. When you click on the icon it reads the JSON file. There is a slight lag in this. I'm not sure putting the config in ram is the best solution. 

I do think that their is improvement in this area.

@fitztrev I was thinking about moving the code base to swift. How would you feel about this? There could be optimization gains in moving to swift.

**Comment by thshdw** [comment]
@FezVrasta I'm going to close this for now and put it on hold.
