### ISSUE TITLE
Add option to "open_in" for "tmux" "pane" or "window"

### ISSUE THREAD

**Issue by challsted** [fitztrev/shuttle#150]
As an avid TMux user already, this app would only be a killer feature if it also had an option to interact with tmux (2.1+ preferably)

**Comment by thshdw** [comment]
Hi @hackinginformation I dont use TMux but what if you made a shuttle command that did this 
```
tmux attach \; new-window vim
```

**Comment by hackinginformation** [comment]
I will attempt this when I'm at my Mac again (after the holiday)
Sorry, not used to getting notifications on GH, didn't think to look at what the blue circle meant  
Thanks for the attempt thus far.

**Comment by thshdw** [comment]
@challsted 
did making a command with this directive work for you?
```
tmux attach \; new-window vim
```

**Comment by challsted** [comment]
@thshdw not that this is helpful in anyway, but my team has moved away from Shuttle for various reasons not specific to Shuttle. 

I never did get time to implement this in testing. 

Thank you for your time in this and the continuous followups :+1:

**Comment by thshdw** [comment]
@challsted You're Welcome and thanks for closing the issue!
