### ISSUE TITLE
sshfuse commands are not allowed in new version

### ISSUE THREAD

**Issue by andreasisaak** [fitztrev/shuttle#151]
The following command is not allowed any more:

"cmd": "sshfs xxx@xxx.xxx.com:/home/user/public_html/ ~/MountingPoints/Servername -olocal,reconnect,defer_permissions,noappledouble,negative_vncache,volname=Servername; exit",

**Comment by thshdw** [comment]
Are you getting any error messages?

**Comment by thshdw** [comment]
@andreasisaak Regarding this issue I think its related to #153 are you getting the same error as #153 ?

**Comment by thshdw** [comment]
This should be fixed in release v.1.2.6 pull #165
