### ISSUE TITLE
URLs are not correctly detected. 

### ISSUE THREAD

**Issue by digitalhitler** [fitztrev/shuttle#153]
Hello!
Thanks for great app of my dream :)
I have an issue with iTerm configuration: it just don't works and I got this:

![screen shot 2015-11-28 at 11 16 33 pm](https://cloud.githubusercontent.com/assets/1048856/11453701/26107e02-9626-11e5-9f36-a50fc9c36205.png)

(`nowhere` is a command I tried to execute)

Part of configuration:
```
	"terminal": "iTerm",
	"iTerm_version": "nightly",
	"open_in": "tab",
	"launch_at_login": true,
	"show_ssh_config_hosts": true,
```
Works great with basic Terminal.app. 
I have latest nightly iTerm 2 release and ```OS X 10.11.1```. Tried to:
* use `stable` as version
* reinstall iTerm shell integration
* assign iTerm with ssh:// URLs
and nothing helps :(

Thanks for advance!

**Comment by thshdw** [comment]
If you don't mind could you send me your not working .JSON file. My email address is on my github page.  Having your json file will help me troubleshoot the issue.

**Comment by digitalhitler** [comment]
Thats it: 
```
{
	"_comments": [
		"Valid terminals include: 'Terminal.app' or 'iTerm'",
		"Hosts will also be read from your ~/.ssh/config or /etc/ssh_config file, if available",
		"For more information on how to configure, please see http://fitztrev.github.io/shuttle/"
	],
	"terminal": "iTerm",
	"iTerm_version": "stable",
	"open_in": "tab",
	"launch_at_login": true,
	"show_ssh_config_hosts": true,
	"ssh_config_ignore_hosts": [],
	"ssh_config_ignore_keywords": [],
	"hosts": [
		{
			"name": "My Dev Server",
			"cmd": "ssh username@dev.example.com"
		},
		{
			"Transmit disk": [
				{
					"name": "192.168.1.2",
					"cmd": "nowhere"
				},
				{
					"name": "Kill all",
					"cmd": "killall -c \"Transmit Disk\""
				}
			]
		},
		{
			"Personal": [
				{
					"name": "My blog",
					"cmd": "ssh username@blog.example.com"
				},
				{
					"Spouse": [
						{
							"name": "Her blog",
							"cmd": "ssh username@blog2.example.com"
						}
					]
				}
			]
		},
		{
			"Vagrant": [
				{
					"name": "precise32",
					"cmd": "ssh vagrant@127.0.0.1 -p 2222 -i ~/.vagrant.d/insecure_private_key"
				}
			]
		}
	]
}
```

**Comment by madhur** [comment]
Same here, can't get the iTerm to work. Using latest nightly. Here is my json file.

```
{
  "_comments": [
    "Valid terminals include: 'Terminal.app' or 'iTerm'",
    "In the editor value change 'default' to 'nano', 'vi', or another terminal based editor.",
    "Hosts will also be read from your ~/.ssh/config or /etc/ssh_config file, if available",
    "For more information on how to configure, please see http://fitztrev.github.io/shuttle/"
  ],
  "editor": "subl",
  "iTerm_version": "nightly",
  "launch_at_login": true,
  "show_ssh_config_hosts": true,
  "ssh_config_ignore_hosts": [  ],
  "ssh_config_ignore_keywords": [  ],
  "terminal": "iTerm",
  "hosts": [
    
  ]
}
```

**Comment by thshdw** [comment]
@madhur Are you passing a theme?

**Comment by thshdw** [comment]
@digitalhitler 
You say ```I have latest nightly iTerm 2 release and OS X 10.11.1```
Make sure you change your version to nightly ```  "iTerm_version": "nightly",```
Regarding your error screenshot... change ```"nowhere"``` to a command like ```"ps aux | grep foo"```

After changing the version to nightly and ```"nowhere"``` to a command your config is working for me. Please contact me if you have questions

**Comment by thshdw** [comment]
@digitalhitler If you want ```nowhere``` to be sent to terminal you need to change the name from                     ```"name": "192.168.1.2",``` too  ```"name": "192 168 1 2",``` Seems there is a bug with numbers in the name of the command.

**Comment by madhur** [comment]
@thshdw I do not see any theme setting in iTerm like the Terminal app.  I do have two profiles

* Madhur
* Hotkey Window

Apart from that, its pretty much default. Exact version is `Build 2.9.20151117-nightly`

**Comment by thshdw** [comment]
@madhur Sorry... :) I meant to ask what your default profile was in iTerm. If its not default then you have to set the default in your json file

**Comment by thshdw** [comment]
@madhur I think what you and @digitalhitler are experiencing are different issues. Regarding @digitalhitler issue... This is a bug in the url checking. Tagging as such. @madhur I think your issue is related to #147

**Comment by thshdw** [comment]
@digitalhitler discovered a bug with the URL detection. shuttle checks the command to see if its a URL then opens that URL in the default app. 
Example: 
```
"cmd": "cifs://myServer/c$"
```
Should open the above path in finder. 
_I have a fix in my sandbox branch but I need to test it for the 1.2.6 release._

**Comment by digitalhitler** [comment]
Huh, so hot discussion here and I am so far from my home to check it. 
Its doesnt matter now but I tried everything before reporting an issue: use real commands, full path to binary, "open" command before my command, stable, nightly builds etc. but i doesnt tried to define url schema before command. 

Thanks! I'll try it when come back home and tell you if it works. Btw, what schema I need to use? Something like `iterm://` or what?

**Comment by digitalhitler** [comment]
I meant any terminal command above, not CIFS connection. E.g. Something like `iterm://uptime`.

**Comment by thshdw** [comment]
@digitalhitler 
In your command you have the following:
```
            "Transmit disk": [
                {
                    "name": "192.168.1.2",
                    "cmd": "nowhere"
                },
```
This is what happens... ```cmd``` (due to a bug) is not correctly checking if its a URL. The bug incorrectly parses ```name``` (because of the IP address) and uses ```name``` as  a part of the command. The code incorrectly then detects your ```cmd``` as a URL (which it is not) and then tries to open your ```cmd``` in the default application. 

Unless you are trying to open a url like a website or a file path your solution would be to take the ```.``` out of your ```name``` and replace them with spaces.  ```"name": "192 168 1 2",```

**Comment by digitalhitler** [comment]
Oh, yeah, now I've got understood you, thanks a lot for detailed explanation for slowies like me.

**Comment by thshdw** [comment]
@digitalhitler You're welcome! Thanks for discovering the issue. :+1:

**Comment by thshdw** [comment]
fixed in release v.1.2.6 pull #165
