### ISSUE TITLE
Add an IGNORE keyword to the shuttle comment syntax

### ISSUE THREAD

**Issue by QuChao** [fitztrev/shuttle#156]
There are some config lines from my ~/.ssh/config file:

```
Host svr01
    # shuttle.name = vps/svr01
    HostName 10.250.*
Host svr02
    # shuttle.name = vps/svr02
    HostName 10.251.*
Host svr01 svr02
    Port 2222
```

It shows a nested menu in shuttle which is useful enough,
however an unexpected item named 'svr01 svr02' shows up in the root too.
I found `ssh_config_ignore_hosts` & `ssh_config_ignore_keywords` can solve this problem,
and I also think a keyword like `# shuttle.ignore` could do the same thing more conveniently?

Thanks for your great works!

**Comment by thshdw** [comment]
Hi @QuChao 
@keesfransen contributed #154 this will be in the next release and should solve your issue. :smile:
