### ISSUE TITLE
Regarding preferences

### ISSUE THREAD

**Issue by madhur** [fitztrev/shuttle#157]
Just a question, why are you not using a UI window which uses `NSUserDefaults` to store the preferences instead of a `.shuttle.json` file ?

**Comment by thshdw** [comment]
Hi @madhur 
with the recent changes shuttle now has two sets of options. 
1. Global Settings. 
2. Command level Settings. 

Eventually Global settings with most likely be placed in the user interface; as you suggest. 
Command level settings will stay in the JSON file. Some users have several commands and scripts in nested menus and all this is much more elegant and easy to edit in the JSON file.

**Comment by madhur** [comment]
:+1:
