### ISSUE TITLE
Commands not working when iTerm running

### ISSUE THREAD

**Issue by highacid** [fitztrev/shuttle#160]
Hello,

I have the following config, and nothing works.

{
  "_comments": [
    "Valid terminals include: 'Terminal.app' or 'iTerm'",
    "In the editor value change 'default' to 'nano', 'vi', or another terminal based editor.",
    "Hosts will also be read from your ~/.ssh/config or /etc/ssh_config file, if available",
    "For more information on how to configure, please see http://fitztrev.github.io/shuttle/"
  ],
  "editor": "default",
  "launch_at_login": true,
  "terminal": "iTerm",
  "iTerm_version": "nightly",
  "default_theme": "Solarized Light",
  "open_in": "new",
  "show_ssh_config_hosts": false,
  "ssh_config_ignore_hosts": [  ],
  "ssh_config_ignore_keywords": [  ],
  "hosts": [
    {
      "cmd": "ps aux | grep defaults",
      "name": "Grep - Opens in Default-window-theme-title"
    },
    {
      "DEV": [
        {
          "cmd": "echo '—->WARNING<-- Running a command in this active terminal! Are you sure? y/n'; read sure; if [ $sure == y ]; then echo running command... && tail -f /var/log/current; else echo exiting...; fi",
          "inTerminal": "current",
          "name": "Logs - Opens in the current active terminal window"
        },
        {
          "DNS": [
            {
              "cmd": "ssh root@dns2.uhlhosting.ch -p 77 -i ~/.ssh/id_rsa",
              "inTerminal": "new",
              "name": "SSH DNS2",
              "theme": "basic",
              "title": "title of tab"
            },
            {
              "cmd": "ssh root@dns1.uhlhosting.ch -p 77 -i ~/.ssh/id_rsa",
              "inTerminal": "new",
              "name": "SSH DNS1",
              "theme": "basic",
              "title": "title of tab"
            }
          ]
        }
      ]
    },
    {
      "WHM": [
        {
          "cmd": "ssh root@5.196.111.219 -p 77 -i ~/.ssh/id_rsa",
          "name": "WHM/cPanel",
          "inTerminal": "tab",
          "name": "SSH WHM",
          "theme": "basic",
          "title": "title of tab"
        }
      ]
    }
  ]
}

**Comment by thshdw** [comment]
Hi @highacid 
Currently I don't have any error correction regarding the themes. So if iTerm nightly does not have theme ```basic``` then your command won't run. Make sure that in your iTerm you have the themes you set in the JSON. Themes / Profiles in iTerm are also case sensitive.

**Comment by highacid** [comment]
@thshdw hello,

I am still unable to make the settings work. I am confused about the themes, since in Settings>Appearance I have only these themes. I have reseted all settings. I have tried also the Beta version, is this working strictly with the nightly build? http://prntscr.com/9r128a please instruct further. I would love to have it working, yet I was not able with all settings and testings made until now.

**Comment by thshdw** [comment]
Ah! You have to keep the Default theme. iTerm ships with one profile called Default for now you have to keep that profile. So add a profile called Defualt, you could copy your Guake profile then call it Guake. Then in you JSON use Guake as your theme 

Sent from Outlook Mobile




On Sat, Jan 16, 2016 at 3:19 PM -0800, "Kosmos" <notifications@github.com> wrote:












@thshdw hello,



I am still unable to make the settings work. I am confused about the themes, since in Settings>Appearance I have only these themes. I have reseted all settings. I have tried also the Beta version, is this working strictly with the nightly build? http://prntscr.com/9r128a please instruct further. I would love to have it working, yet I was not able with all settings and testings made until now.

**Comment by highacid** [comment]
@thshdw I have managed to make it work, maybe by updating documentation at some point with a visual help would be great. Thanks for amazing tool!

**Comment by highacid** [comment]
My god... I lost it again, not sure if changing from new to tab:


====

{
  "_comments": [
    "Valid terminals include: 'Terminal.app' or 'iTerm'",
    "In the editor value change 'default' to 'nano', 'vi', or another terminal based editor.",
    "Hosts will also be read from your ~/.ssh/config or /etc/ssh_config file, if available",
    "For more information on how to configure, please see http://fitztrev.github.io/shuttle/"
  ],
  "editor": "default",
  "launch_at_login": true,
  "terminal": "iTerm",
  "iTerm_version": "stable",
  "default_theme": "Default",
  "open_in": "new",
  "show_ssh_config_hosts": false,
  "ssh_config_ignore_hosts": [  ],
  "ssh_config_ignore_keywords": [  ],
  "hosts": [
    {
      "cmd": "ps aux | grep defaults",
      "name": "Grep - Opens in Default-window-theme-title"
    },
    {
      "DEV": [
        {
          "cmd": "echo '—->WARNING<-- Running a command in this active terminal! Are you sure? y/n'; read sure; if [ $sure == y ]; then echo running command... && tail -f /var/log/current; else echo exiting...; fi",
          "inTerminal": "current",
          "name": "Logs - Opens in the current active terminal window"
        },
        {
          "DNS": [
            {
              "cmd": "ssh root@dns2.uhlhosting.ch -p 77 -i ~/.ssh/id_rsa",
              "inTerminal": "new",
              "name": "SSH DNS2",
              "theme": "Default",
              "title": "title of tab"
            },
            {
              "cmd": "ssh root@dns1.uhlhosting.ch -p 77 -i ~/.ssh/id_rsa",
              "inTerminal": "new",
              "name": "SSH DNS1",
              "theme": "Default",
              "title": "title of tab"
            }
          ]
        }
      ]
    },
    {
      "WHM": [
        {
          "cmd": "ssh root@5.196.111.219 -p 77 -i ~/.ssh/id_rsa",
          "name": "WHM/cPanel",
          "inTerminal": "new",
          "name": "SSH WHM",
          "theme": "Default",
          "title": "title of tab"
        }
      ]
    }
  ]
}
====

I lost it after I managed to use it once or twice... Why is so complex to configure it... And why is loosing so fast... No idea. :)

**Comment by thshdw** [comment]
@highacid lets jump on chat

**Comment by highacid** [comment]
@thshdw sure, what client? skype? fb? whatsup?

**Comment by thshdw** [comment]
@highacid on the main page there is the git chat badge or here https://gitter.im/fitztrev/shuttle?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by highacid** [comment]
This works as designed now Issue solved.
