### ISSUE TITLE
Parse multiple ssh_config files using the new Include directive

### ISSUE THREAD

**Issue by thshdw** [fitztrev/shuttle#162]
Requested by @skebi69 

ssh_config files are ubiquitous it would be nice if shuttle could parse more than one file with ssh_config syntax. 

Your system can only read the primary file ssh_config (unless to conjugated them into one) but it would be beneficial for shuttle to make menus from multiple ssh_configs 

Possible example in shuttle's JSON
“Spouses Servers” : “ssh_config_file” = “~/.ssh/spouse_config"

**Comment by FlxPeters** [comment]
+1

**Comment by FlxPeters** [comment]
maybe a include option for another config file would be great. Something like:
```
"hosts": @include:myHostFile.json
```

**Comment by thshdw** [comment]
I was thinking more of adding this to the global settings section something like:
```
"ssh_config_1": "~/.ssh/work-config",
"ssh_config_2": "~/.ssh/spouse-config"
```

```
"json_config_1": "~/.shuttle-work.json"
"json_config_2": "~/.shuttle-presonal.json"
```

**Comment by skebi69** [comment]
+1 to adding ssh_config_1 to the global settings.

**Comment by thshdw** [comment]
@skebi69 Thanks, I too think that this is the best way to handle this. I expect to get around to this sometime this summer.

**Comment by cthoyt** [comment]
I would also love to be able to define an alternate location for the `.shuttle.json` configuration; probably somewhere like `~/.config/shuttle/config.json` so as to de-clutter my home directory from excessive dotfiles.

**Comment by thshdw** [comment]
@cthoyt if your looking change the path of ```.shuttle.json``` you can do this here https://github.com/fitztrev/shuttle/wiki/Settings-and-Configuration it requires the creation of a dotfile

In your home directory create a file called ~/.shuttle.path In this file should be a single line with the path to the JSON settings file.

**Comment by cthoyt** [comment]
That's a nice tweak that I'm sure is useful for other purposes, but that would leave my +/- on the number of files in the home directory at 0 😂 Thanks for the help though

**Comment by Pimentoso** [comment]
+1, at work we are required to symlink the shuttle config from a shared file, I'd like to add my personal entries to the menus (thus extending the default config file)

**Comment by darkwinternight** [comment]
Starting with `ssh 7.3` (released on August 1st, 2016), an `Include` directive is available in ssh `config` files.

> **Include:** Include the specified configuration file(s). Multiple path names may be specified and each pathname may contain glob wildcards and shell-like "`~`" references to user home directories. Files without absolute paths are assumed to be in `~/.ssh`. An  Include directive may appear inside a `Match` or `Host` block to perform conditional inclusion.

(Here is the link to the resolved bug report, that also includes the patch: https://bugzilla.mindrot.org/show_bug.cgi?id=1585#c24)

Would be nice if this was supported! It seems cleaner (and solves my use case, which is the same one as @Pimentoso's) than the proposed solution.

**Comment by lovelock** [comment]
I have wrote a cli ssh connection manager which based on `.ssh/config`, so I have a heavily configured file. Today I found shuttle, docs say it will read ssh/config file, but I find it not. After I add some hosts to `.shuttle.json`, all the local port forwarding config is lost.

**Comment by thshdw** [comment]
@lovelock I think this is a separate issue.

**Comment by julien-c** [comment]
Hi @thshdw @fitztrev first of all, thanks for your awesome work on Shuttle so far.

I would like to take a look at this issue (support for ssh's Include directive). Would you be willing to merge if I submit a PR?

**Comment by julien-c** [comment]
@otherguy @Pimentoso, check out #238 and let me know if this solves your use case.

**Comment by thshdw** [comment]
Awesome! Thanks @julien-c

**Comment by alex-mohemian** [comment]
@julien-c awesome, thanks! 👍 

Any way to get a new release (for my work computer)?
