### ISSUE TITLE
Shuttle not parsing my config file

### ISSUE THREAD

**Issue by williamn** [fitztrev/shuttle#166]
Hi @fitztrev,

Thanks for this great work.

I have a small issue here.

Shuttle is not parsing my `~/.ssh/config`, it doesn't display the hosts defined there.

Here is my `~/.ssh/config`

```
Host work/foo
    User user1
    Hostname github.com
    IdentityFile ~/.ssh/github-1.key
```

and here is my shuttle.json

```json
{
	"launch_at_login": true,
	"terminal": "iTerm",
	"iTerm_version": "stable",
	"show_ssh_config_hosts": true
}
```

Any idea why?

Thanks!

**Comment by thshdw** [comment]
Hi @williamn ssh config parsing is working for me...
Questions:
1) Are you using the latest version?
2) Are you wanting shuttle to only parse your ssh config? Your shuttle.json seems empty only showing settings. If this is your intention then your shuttle.json needs to look like this:
```
{
  "iTerm_version": "stable",
  "launch_at_login": true,
  "show_ssh_config_hosts": true,
  "terminal": "iTerm",
  "hosts": [
    {
    }
  ]
}
```
3) If you want to have some hosts in your shuttle.json a barebones version would look like this:
```
{
  "iTerm_version": "stable",
  "launch_at_login": true,
  "show_ssh_config_hosts": true,
  "terminal": "iTerm",
  "hosts": [
    {
      "Folder": [
        {
          "cmd": "ssh user@example.org",
          "name": "server 1"
        }
      ]
    }
  ]
}
```

**Comment by williamn** [comment]
Hi @thshdw,

1. I'm using version 1.2.6
2. I change my shuttle.json per your instruction and now its works

Thank you!

**Comment by thshdw** [comment]
@williamn You're Welcome, thanks for the update!
