### ISSUE TITLE
Chaining commands \ Login script

### ISSUE THREAD

**Issue by gah242s** [fitztrev/shuttle#169]
I feel stupid, but I can't find an example for this.  I've got the menus built and logins working as I want.  However, how do add commands to run after successful login?  There are certain clients that I want to run a command, or string of commands, every time I log in.  A quick and dirty example would be to sudo.

**Comment by thshdw** [comment]
@gah242s There are no stupid questions here, ask anything! 😄 

Some questions... 
) do you want to run the commands exactly after you log in? 

) do you want to run the commands from the shuttle menu after you log in?

**Comment by gah242s** [comment]
Both? The initial impetus was wanting to run the command immediately after login, essentially as part of the login process.  A second thought was a script that could be created, say an update script, that could be run across multiple machines.

**Comment by thshdw** [comment]
@gah242s You could do this a few ways.

### expect
```
#!/usr/bin/expect -f

spawn ssh myUser@ServerName.myDomain.com
expect {
"myUser" {send "ps aux | grep ssh && exit\r";exp_continue}
}
```
call the above with expect ```expect /tmp/myscript.txt``` this would ssh you to the system and and run ```ps aux | grep ssh``` show you the output and then log you out. 

### ForceCommand 
sshd has something called force command. In the sshd_config on the server you tell ForceCommand the script you want to run...
```
     ForceCommand
	     Forces the	execution of the command specified by ForceCommand,
	     ignoring any command supplied by the client and ~/.ssh/rc if
	     present.  The command is invoked by using the user's login	shell
	     with the -c option.  This applies to shell, command, or subsystem
	     execution.	 It is most useful inside a Match block.  The command
	     originally	supplied by the	client is available in the
	     SSH_ORIGINAL_COMMAND environment variable.	 Specifying a command
	     of	``internal-sftp'' will force the use of	an in-process sftp
	     server that requires no support files when	used with
	     ChrootDirectory.  The default is ``none''.
```

### bashrc
see here http://stackoverflow.com/questions/820517/bashrc-at-ssh-login

### shuttle and the inTerminal: current setting
```"inTerminal": "current"``` is a command level setting that will tell shuttle to run your command in the existing window. So you would use a shuttle command to ssh to the server and then use shuttle again to run your command in the currently open terminal window. While not automated like expect and ForceCommand it's very resuable with no configurations needed server side. For more on this see https://github.com/fitztrev/shuttle#interminal-value

**Comment by thshdw** [comment]
I think that this is resolved.... if not please reopen 😄
