### ISSUE TITLE
[Request] Shuttle for Windows 10

### ISSUE THREAD

**Issue by edgr-sanchez** [fitztrev/shuttle#171]
My main computer is a Mac and I use Shuttle multiple times a day to manage dozens of servers over SSH using iTerm2. 

When I'm traveling, I use a Surface Pro 4 which has nothing remotely close to Shuttle.

Now that Microsoft is bundling Bash/Ubuntu in Windows 10, is there any chance that you'd be willing to look into creating a version of Shuttle for Windows 10?

![screenshot](http://www.tenforums.com/attachments/software-apps/73665d1460071069t-installing-running-bash-windows-10-build-14316-a-windows10_ssh_terminal.png)

I feel like releasing Shuttle for Windows would be huge, since there's nothing else like it.

It would become a standard app for Windows devs who need to connect to other servers via SSH.

**Comment by thshdw** [comment]
I would be willing to consider doing something in C# and .net. However the timeline on this would be awhile. 

Have you seen the [cmder](http://cmder.net) project. I would lean more towards having "shuttle for windows" spawn in cmder. This way we could have support for windows 7, 8 and 10.

**Comment by edgr-sanchez** [comment]
Yup, I actually use Cmder and Cygwin quite a bit.

Bash for Windows is still a bit rough and it uses the standard Command Prompt shell, which is horrible compared to Cmder and iTerm.

**Comment by thshdw** [comment]
Okay, cool... I think that spawning cmder would be be the best direction. We could always have a toggle so you could spawn the emulator of your choice. Any objections to C# and .net?

**Comment by edgr-sanchez** [comment]
No objections here. Thanks for considering it. 

The toggle is a great idea as I'm sure users running Windows 7/8 would appreciate being able to use Cmder.

Windows 10 users will get the option to use Cmder as well or use the built in Bash client without having to install extra software.

I know Shuttle for Mac is free but you could set up a system for early access/beta testing where people could pay a few bucks to join. I'd definitely join in.

Would probably help development.

**Comment by thshdw** [comment]
Thanks! I'll have to chat with @fitztrev about the general direction. I think though that I'll get an alpha going on my github hub page. I would consider Alpha something that can parse JSON and launch a simple command. Beta would extend the feature set. Stable should be able parse the same JSON as the OSX version, minus the iTerm stuff. shuttle is free and "shuttle for windows" would the same. Once the alpha is functional, I'll make it public on my github page and users can contribute.

**Comment by thshdw** [comment]
The documented way to launch a command using Cmder is through a helper batch file. Then you call this batch file with your command example:

```cmderLauncher.bat "echo foo"``` 

See https://github.com/cmderdev/cmder/issues/457 for details.

**Comment by thshdw** [comment]
@edgr-sanchez I'll be using the method listed above to launch commands in Cmder in the Windows version of shuttle.

**Comment by thshdw** [comment]
Hi @edgr-sanchez I'm closing the issue here moving too https://github.com/thshdw/shuttle-for-windows

We can discuss the alpha here https://github.com/thshdw/shuttle-for-windows/issues/1

Thanks!
