### ISSUE TITLE
cmd with comma

### ISSUE THREAD

**Issue by bonaime** [fitztrev/shuttle#173]
Hi,
Is it possible to use a cmd with a comma ? I want to do
ssh -XC -c blowfish-cbc,arcfour -YX  toto@tata.com

Shuttle parser does not like my comma :-(

**Comment by skebi69** [comment]
I should think that adding Ciphers to .ssh/config would be the best way to go, overall. You can add both Ciphers and ForwardX11Trusted to simplify your ssh command.

**Comment by thshdw** [comment]
@bonaime I'm going to agree with @skebi69 and suggest that you should use the ssh config file for this. However you bring up a good point that the JSON parser is not liking the ```,``` 

I think you have exposed a bug in the parser.

**Comment by thshdw** [comment]
I found the bug and will have a fix in the next release.

**Comment by thshdw** [comment]
Closed! fixes are in 1.2.7
