### ISSUE TITLE
Iterm3 and Shuttle 

### ISSUE THREAD

**Issue by patrickholway** [fitztrev/shuttle#176]
Wondering if shuttle will work with iterm 3 - iterm3 opens briefly and then closes when launched via shuttle.

my settings are: 

    "terminal": "iTerm",
    "iTerm_version": "nightly", //stable doesn't fix it 
    "open_in": "tab",
    "launch_at_login": true,

**Comment by patrickholway** [comment]
Sorry iterm2 v3

**Comment by mkubarycz** [comment]
also having similar issues

	"terminal": "iTerm",
	"launch_at_login": true,
	"show_ssh_config_hosts": true,
	"ssh_config_ignore_hosts": [],
	"ssh_config_ignore_keywords": [],

**Comment by thshdw** [comment]
Hello, 
What shuttle version do you have? 
I'm working with iTerm Nightly v3 builds. See this thread. https://github.com/fitztrev/shuttle/issues/174 also see this pull https://github.com/fitztrev/shuttle/pull/175

You either have iTerm_version missing from your JSON or you have "Don't Open Any Windows" settings turned on in iTerm. New newer versions of shuttle have a lot of new options. make sure you see the readme.md

**Comment by thshdw** [comment]
Here is the demo config that I'm using with iTerm v3 Nightly... Note I have not tested beta builds. Only the nightlies. 

If the config below is not working for you make sure you have a profile called Default and ensure that you dont have the setting "Don't Open Any Windows" turned in 

```
{
  "_comments": [
    "Valid terminals include: 'Terminal.app' or 'iTerm'",
    "In the editor value change 'default' to 'nano', 'vi', or another terminal based editor.",
    "Hosts will also be read from your ~/.ssh/config or /etc/ssh_config file, if available",
    "For more information on how to configure, please see http://fitztrev.github.io/shuttle/"
  ],
  "editor": "default",
  "launch_at_login": false,
  "terminal": "iTerm",
  "iTerm_version": "nightly",
  "default_theme": "Default",
  "open_in": "tab",  
  "show_ssh_config_hosts": false,
  "ssh_config_ignore_hosts": [  ],
  "ssh_config_ignore_keywords": [  ],
  "hosts": [
    {
      "cmd": "ps aux | grep defaults",
      "name": "Grep - Opens in Default-window-theme-title"
    },
    {
      "Spouses Servers": [
        {
          "cmd": "echo '—->WARNING<-- Running a command in this active terminal! Are you sure? y/n'; read sure; if [ $sure == y ]; then echo running command... && tail -f /var/log/current; else echo exiting...; fi",
          "inTerminal": "current",
          "name": "Logs - Opens in the current active terminal window"
        },
        {
          "Jane’s Servers": [
            {
              "cmd": "ssh username@blog2.example.com",
              "inTerminal": "tab",
              "name": "SSH blog - Opens in Tab of active window",
              "theme": "basic",
              "title": "title of tab"
            },
            {
              "cmd": "ssh username@shop1.example.com",
              "inTerminal": "new",
              "name": "SSH Shop - Opens in New Window",
              "theme": "basic",
              "title": "title of new window"
            }
          ]
        }
      ]
    },
    {
      "Vagrant": [
        {
          "cmd": "ssh vagrant@127.0.0.1 -p 2222 -i ~/.vagrant.d/insecure_private_key",
          "name": "Vagrant - Opens in default-window-theme-title"
        }
      ]
    }
  ]
}
```

**Comment by patrickholway** [comment]
Shuttle 1.26 - ill mess with my term settings and respond.

**Comment by thshdw** [comment]
@patrickholway Thanks, try the demo config I just posted and let know if that is working.

**Comment by bendevos** [comment]
it doesn't work with iterm2 build3
thanks

**Comment by jagranata** [comment]
@thshdw The demo config you posted above worked for me with iTerm2 Build 3.0.0.  Was not working at first because I had not iTerm2 profiled named "Default".

**Comment by Ilyes512** [comment]
Oh, it works for me after setting my profile from "Code" back to "Default". I also set iTerm_version to nightly. Yay, can log into my servers with ease again 👍

**Comment by bendevos** [comment]
still not working for me... Here is my config 

```
{
	"_comment1": "Valid terminals include: 'Terminal.app' or 'iTerm'",
	"_comment2": "Hosts will also be read from your ~/.ssh/config or /etc/ssh_config file, if available",
	"_comment3": "For more information on how to configure, please see http://fitztrev.github.io/shuttle/",
  	"editor": "default",
	"terminal": "iTerm",
  	"launch_at_login": false,
	"iTerm_version": "nightly",
  	"default_theme": "Default",
  	"open_in": "tab",  
	"hosts": [
		{
```

**Comment by od3n** [comment]
thanks @thshdw it's working for me

**Comment by bendevos** [comment]
Ok i needed to upgrade shuttle as well. Now it is working Thanks all

**Comment by patrickholway** [comment]
@thshdw Yes it was my profile - it was called local. I changed it to Default and changed the iterm setting to nightly. This was the ticket. Thanks so much. Not sure what I would do without shuttle .... 👍 

<img width="409" alt="screenshot 2016-06-06 09 09 21" src="https://cloud.githubusercontent.com/assets/10289568/15822941/7d0a5940-2bc6-11e6-85ba-b3ec9668670a.png">

**Comment by BitBrit** [comment]
@thshdw I have the exact same config file as yours (except for the hosts parts) and yet my Shuttle still doesn't work. All it does is focus iTerm but doesn't create a new tab or insert the ssh line. I am using Shuttle 1.2.6.

Is there anything else I can check?

**Comment by thshdw** [comment]
@BitBrit Make sure that in iTerm you have a profile called Default and that its set as the default profile

**Comment by thshdw** [comment]
@patrickholway @od3n @bendevos @Ilyes512 I'm happy its working for you and Thank you for the feedback.

**Comment by BitBrit** [comment]
@thshdw Thanks for that, it worked. Default wasn't set as default. That did the trick. Many thanks for the prompt response. I love shuttle, would have been mucho sad if it went away.

**Comment by thshdw** [comment]
@BitBrit Awesome, thanks for the feedback! I'm happy its working for you! 😃

**Comment by moleculezz** [comment]
It works.. except that it doesn't open in tabs. Each time it opens a new window.

**Comment by patrickholway** [comment]
Change your shuttle config to open in tab

**Comment by thshdw** [comment]
@moleculezz see the all the new directives in the readme.md


```"open_in": "VALUE",```
This changes the default action for how commands are opened (Global Setting)
Possible values are ```tab``` or ```new```.
tab opens the command in the active terminal in a new tab.
new opens the command in a new window.

This setting can be overwritten by the command level "inTerminal" settings

**Comment by patrickholway** [comment]
these are mine

  "terminal": "iTerm",
  "iTerm_version": "nightly",
  "open_in": "tab",
  "launch_at_login": true,

**Comment by thshdw** [comment]
Thanks @patrickholway 
@moleculezz these new directives were added so you can have more flexible window handling. Maybe you want all commands to open in tabs... but perhaps there is one special command that you want to have opened in a separate window with a different theme. You can do this now with ```"open_in": "VALUE",``` and ```"inTerminal": "VALUE",```

**Comment by moleculezz** [comment]
I see what happened. I had it defined twice in my config. One as `tab` and further in the config as `new`. It picked up the last setting which is understandable.

**Comment by thshdw** [comment]
@moleculezz Thanks for the feedback, I'm happy its working for you now :+1:

**Comment by thshdw** [comment]
Hi All, 

I'm going to close this. iTerm 3 and shuttle are working. Just make sure that:

* You have the latest version currently 1.2.6 and your shuttle.JSON is correct. See the readme.md which goes over all the new directives. 

* If you have changed the default theme in iTerm  you need to have that same Profile listed in your shuttle.JSON as the global default theme. 

* If you don't want to set a theme in your shuttle.JSON you need to make sure that iTerm has a profile and that profile is called ```Default``` with a capital ```D``` If theme settings are missing from shuttle.JSON then shuttle passes the Default theme. On a clean install of iTerm the default Profile is called ```Default``` If ```Default``` is missing or renamed from iTerm and shuttle is not told what theme to use then shuttle's applescripts fall back to the built in default Profile. If that profile is missing or renamed then your command won't run.  

I'm repeating because its important. If you have changed the default theme in iTerm you have two choices. 
* Tell shuttle what iTerm's new default Profile is called using the global setting directive ```"default_theme": "Homebrew",``` here i'm telling shuttle that I've changed iTerm's default theme to ```Homebrew```

* If you don't care about themes and don't want to mess around with themes in your shuttle.JSON; then shuttle is going to try to use iTerm's default which is called ```Default```. if that is missing or called something other than ```Default``` you need to change it back so iTerm's default profile is called ```Default``` 

If you have questions about this please contact me.

**Comment by unslur** [comment]
change iterm2 profile name is "Defalut"
