### ISSUE TITLE
Doesn't work with iTerm2 (3.0.2) at el capitan

### ISSUE THREAD

**Issue by vicmosin** [fitztrev/shuttle#179]
Have latest Shuttle 1.2.6 release. iTerm is set as default shell editor.
Commands such as `ssh url` open the iTerm window but no actual commands there, just default you have new email...

**Comment by thshdw** [comment]
@vicmosin I never received an email from you. 

Could you send me your ```shuttle.json``` file. Also check out this issue. https://github.com/fitztrev/shuttle/issues/176 and this pull https://github.com/fitztrev/shuttle/pull/175

If your are coming from an really old version make sure your shuttle.json has ```"iTerm_version":"nightly"``` also make sure that your global settings reflect the default profile in iTerm or make sure that your iTerm has a default profile and that profile is called "Default" also make sure that your iTerm is not set ```Don't Open Any Windows``` in  Preferences/General/Startup

Please check these things and report back.

**Comment by chris-short** [comment]
I had the same issue and can confirm changing the iTerm version to nightly worked for me.

**Comment by vicmosin** [comment]
`"iTerm_version":"nightly"` indeed solves the problem

**Comment by thshdw** [comment]
Awesome, Thanks for the updates!
