### ISSUE TITLE
On El Capitan isn't working

### ISSUE THREAD

**Issue by pabloleone** [fitztrev/shuttle#180]
I just configured my SSH keys, the top bar menu shows correct and the examples also, but when I click on them nothing happens.

Where can I go to see logs or errors to share with you?

Thank you.

**Comment by thshdw** [comment]
Hi @pabloleone When you say nothing happens what do you mean exactly? No terminal windows open or a terminal window opens but your not getting connected ie your command is not running? 

What terminal are you using?

**Comment by pabloleone** [comment]
Just nothing. No terminal, nothing. I downloaded the code and it doesn't work from xcode either and sadly I don't know objective c. I ran the app using xcode and there's no issues.

The examples don't work.

**Comment by thshdw** [comment]
If you have a really old version of shuttle you will have to update your shuttle.json to have the nightly directive "iTerm_version":"nightly"  Also check out this issue. #176 and this pull #175

Also make sure that your global settings reflect the default profile in iTerm or make sure that your iTerm has a default profile and that profile is called "Default" also make sure that your iTerm is not set Don't Open Any Windows in Preferences/General/Startup

I'm using 10.11.5 and I have iTerm 3 nightly everything is working so it seems that its a configuration problem. 

Please check these things and report back.

**Comment by pabloleone** [comment]
Thank you, the issue was the iTerm_version value, I just updated with nightly value and everything is working.

**Comment by thshdw** [comment]
@pabloleone You're welcome, Awesome! Thanks for the update.
