### ISSUE TITLE
.ssh/config not parsing username based on documentation

### ISSUE THREAD

**Issue by hhakeem** [fitztrev/shuttle#182]
Using the format for .ssh/config file. I kept receiving error in which a specified username was not being passed to the terminal ssh command. If the username is left off, then it would use the current terminal user username as normal.  

Error: ssh: Could not resolve hostname user@web01.example.com: nodename nor servname provided, or not known

Host work/servers/web01
        HostName user@web01.example.com
- or -

Host gandalf
        # shuttle.name = work/servers/web01 (webserver)
        HostName user@web01.example.com

Changing the format to below resolved that for me. 

Host username@gandalf
        # shuttle.name = work/servers/web01 (webserver)
        HostName web01.example.com

**Comment by thshdw** [comment]
@hhakeem What version are you using? I want to test for regressions.

**Comment by hhakeem** [comment]
1.2.6

**Comment by thshdw** [comment]
Thanks!

**Comment by thshdw** [comment]
@hhakeem Could you test this in v1.2.9 its working for me in the new release.

**Comment by thshdw** [comment]
@hhakeem  I see the issue. I was using the example you provided and assumed that the error ```nodename nor servname provided, or not known``` was because I did not have access. 
Documentation is wrong in the wiki. 
```Hostname 127.0.0.1```
will work but if you need to log in using a specific user you need the user directive so the correct syntax is 

```
Host Testing
# shuttle.name = work/servers/web01 (webserver)
User user1
Hostname 127.0.0.1
```

**Comment by thshdw** [comment]
Documentation fixed 
https://github.com/fitztrev/shuttle/wiki/SSH-Config-File-Settings
Thanks for bringing this to my attention. 😃
