### ISSUE TITLE
Support for HyperTerm

### ISSUE THREAD

**Issue by apfelbox** [fitztrev/shuttle#190]
Hi,

would be nice if shuttle would also support [HyperTerm](https://hyperterm.org/), next to iTerm and Terminal.app.

**Comment by thshdw** [comment]
Does it support AppleScript?

**Comment by thshdw** [comment]
https://github.com/zeit/hyperterm/issues/540 Once it supports apple script I could look into this.

**Comment by thshdw** [comment]
Closing for now... when HyperTerm gets apple script support we can revisit.

**Comment by thshdw** [comment]
I did some digging in the electron issues and found this. https://github.com/electron/electron/issues/4418 seems that this is not happening anytime soon.
