### ISSUE TITLE
Order items manually

### ISSUE THREAD

**Issue by alltry** [fitztrev/shuttle#191]
Hi,
I miss a option to order items manually on menu, it is possible?

**Comment by thshdw** [comment]
Currently this is not possible but it could be. I could add some sorting directive where in the JSON you specify a number and then it sorts based off that number.

Example: 
```"MenuItemNumber": "8"```

Would  anyone else be interested in this feature?

**Comment by thshdw** [comment]
We also have #117 which is sorting based on the order listed in the JSON file. Which method would you prefer?

**Comment by alltry** [comment]
I prefer order JSON file, because I don't use ssh/config file

**Comment by thshdw** [comment]
If shuttle built the menu based on the order in the JSON file would that be adequate?

**Comment by alltry** [comment]
Yes! that's be perfect...

**Comment by thshdw** [comment]
Okay, Thanks for the update!

**Comment by nathanreid** [comment]
Any progress on this? Would be great to have the order based on the order in the JSON file.

**Comment by thshdw** [comment]
@nathanreid No progress yet. I hope to have it in the next release I dont have a timeline for you.

**Comment by thshdw** [comment]
#117 is asking for the same feature. Cleaning up the issues area. Closing this and using #117 as the main for this request.
