### ISSUE TITLE
Create a Line separator

### ISSUE THREAD

**Issue by alltry** [fitztrev/shuttle#192]
Hi,
Is it possible, create a line separator on menu?

**Comment by thshdw** [comment]
I'd have to think about how to implement this. I suppose we could make some directive like separator in JSON similar to your request in #191 ```"Separator": "dotted"``` 

I could see where this could be useful visually but it may be easier to group similar commands in their own submenu, which is currently supported. 

Thoughts?

**Comment by alltry** [comment]
"Separator": "dotted" is a good idea! 
I miss this this options because I came from Linux to OsX, in Linux I used SSHPlus script.

**Comment by thshdw** [comment]
How do you feel about about using menu groups to sort in lieu of a separator?

So you would put all your vagrant boxes in a menu called Vagrant and then when that fly's out in the menu you just have those systems.

**Comment by alltry** [comment]
I use menu groups, but I use a group for each business I take care, but in a group I wish to split some server just with a separator.

**Comment by thshdw** [comment]
Cool! Thanks for the explanation!

**Comment by thshdw** [comment]
@alltry 
Would you want separators in just the main menus like this?

<img width="336" alt="screen shot 2016-10-20 at 4 27 44 pm" src="https://cloud.githubusercontent.com/assets/4992951/19581497/448be80e-96e2-11e6-98c9-635a0fe12359.png">

**Comment by thshdw** [comment]
...or would you want them in the submenus like this?

<img width="686" alt="screen shot 2016-10-20 at 4 43 29 pm" src="https://cloud.githubusercontent.com/assets/4992951/19581777/79e4bc54-96e4-11e6-8dac-9297ae038483.png">

**Comment by thshdw** [comment]
How does everyone feel about this? 
In the name of the menu item you add ```[---]```
```
      "Vagrant": [
        {
          "cmd": "ssh vagrant@127.0.0.1 -p 2222 -i ~/.vagrant.d/insecure_private_key",
          "name": "Vagrant - Opens in default-window-theme-title"
        },
        {
          "cmd": "ssh vagrant@127.0.0.1 -p 2222 -i ~/.vagrant.d/insecure_private_key",
          "name": "Testing - Does some other bit of awesomeness"
        },
        {
          "cmd": "ssh vagrant@127.0.0.1 -p 2222 -i ~/.vagrant.d/insecure_private_key",
          "name": "Foo - My super amazing command rules![---]"
        }
      ]
```
In code we remove ```[---]``` make a boolean to add a separator which looks like this:

<img width="690" alt="screen shot 2016-10-20 at 5 25 22 pm" src="https://cloud.githubusercontent.com/assets/4992951/19582542/3fef94f0-96ea-11e6-993f-9fd787930420.png">

**Comment by alltry** [comment]
Perfect to me, thanks!

**Comment by thshdw** [comment]
Okay! I'll add this to the next release. Thanks for the feedback

**Comment by abecks** [comment]
Would love to have this. Any idea when the next release will be, @thshdw ?

**Comment by thshdw** [comment]
@abecks Probably this weekend... its working on my dev box just need to make some touch ups and compile.

**Comment by thshdw** [comment]
@abecks An update! I encountered some issues and did not make the release. This week for sure though.

**Comment by abecks** [comment]
Happy new year @thshdw. Anything I might be able to do to help bring this feature out? Case of beer?

**Comment by shpoont** [comment]
Would love to see this

**Comment by thshdw** [comment]
Added in https://github.com/fitztrev/shuttle/pull/234
