### ISSUE TITLE
Doesn't work with iTerm2 3.0.7 (stable). Similar to issue #181

### ISSUE THREAD

**Issue by veeramarni** [fitztrev/shuttle#193]
Hi,

I'm using the latest shuttle version (v1.2.7) and iTerm version is up to date (v3.0.7). I couldn't open the iTerm from shuttle, i tried using "stable" and "nightly" as iTerm_version in both cases it neither works. When there is no iTerm2 window opened, it will open it and crashes right away.

**Comment by thshdw** [comment]
Hello @veeramarni in your JSON file is Terminal set to iTerm? 
```"terminal": "iTerm",```

**Comment by veeramarni** [comment]
yes. 
![image](https://cloud.githubusercontent.com/assets/3382355/17833652/fe358b7e-66f0-11e6-9e7e-16e0569285f5.png)

**Comment by thshdw** [comment]
Your ```iTerm_version``` should be stable. Do you have a theme called Homebrew in iTerm? If you don't this will cause issues. 

Confirm that in iTerm you have a profile called ```Default``` and one called ```Homebrew```

**Comment by thshdw** [comment]
@veeramarni Did you get the issue resolved? Did the above work for you?

**Comment by veeramarni** [comment]
No it still don't work. 
![screen shot 2016-08-23 at 2 43 02 pm](https://cloud.githubusercontent.com/assets/3382355/17905147/ef3f8a88-693f-11e6-9a31-5479df914aa0.png)

**Comment by veeramarni** [comment]
I tried theme that exist in iTerm such as Light and Dark but still same issue.

**Comment by thshdw** [comment]
Could you e-mail me your config file? My email address is in my github profile. 

Thanks,

**Comment by veeramarni** [comment]
I have emailed you.

Thanks

**Comment by veeramarni** [comment]
Any update on this issue?

**Comment by thshdw** [comment]
I'm currently testing the next release and I can't duplicate the issue.

**Comment by thshdw** [comment]
I could not duplicate this issue with v1.2.8. Please test the latest release.

**Comment by thshdw** [comment]
Documentation fixed 
https://github.com/fitztrev/shuttle/wiki/SSH-Config-File-Settings
Thanks for bringing this to my attention.

**Comment by thshdw** [comment]
@veeramarni What is the ssh error. I'll be on gitter all day if you want to chat about the issue.

**Comment by thshdw** [comment]
@veeramarni When I load the config that you sent me and I try to log into Personal which is an aws system it asks to accept the key... it looks like its working for me.

**Comment by Rainer-Lang** [comment]
@thshdw Do you have an example for AWS? Where I have to use the pem-file?

**Comment by thshdw** [comment]
@Rainer-Lang I created a new issue for you see #204
