### ISSUE TITLE
Add support for symbolic links

### ISSUE THREAD

**Issue by thshdw** [fitztrev/shuttle#196]
requested by @moll see #110

Currently, changing the path to the .JSON file does not work with symbolic links. While changing the path using shuttle.path works shuttle should correctly work if users change the path using symbolic links.

**Comment by moll** [comment]
👍

**Comment by thshdw** [comment]
Hi @moll 
I'm testing the next release and symbolic links are working as expected. 

When shuttle starts he creates ```~/.shuttle.json``` (assuming it does not exist)

On my system I run:
```ln -s ~/.shuttle.json ~/Desktop/symTest/test.json``` 

I then edit ```test.json```  and check shuttle which was running when I made the edits... and I see my updated changes. 

Are you expecting something different?

**Comment by thshdw** [comment]
Hi @moll 
I have also tested this in reverse..

```mv ~/.shuttle.json  ~/Desktop/newLocation/shuttle.json```
```ln -s ~/Desktop/newLocation/shuttle.json ~/.shuttle.json```

I then edit the shuttle.json in directory newLocation save the file and shuttle is updating the changes.

**Comment by moll** [comment]
Hey!

Thanks. The latter example was what I had in mind and if that works, then that's superb!

**Comment by thshdw** [comment]
@moll 
I'll keep this open till I hear back but it should work for you.

**Comment by moll** [comment]
If you've tested it, I believe you. No need to keep a finished issue open on my part. It might take while till I get around to upgrading software for non-security reasons. ^_^

**Comment by thshdw** [comment]
Thanks! If its not working for you when you have time to test out we can revisit 😄
