### ISSUE TITLE
Shuttle open another APP on hitting settings

### ISSUE THREAD

**Issue by highacid** [fitztrev/shuttle#197]
Hi,

My shuttle open up an App called Dubby I have installed instead of showing me settings. Any idea how to fix this?

**Comment by thshdw** [comment]
@highacid Could I get a little more information?
* Could I seen the JSON entry in your shuttle.json that opens Dubby?
* When you click on the shuttle menu for Dubby What is happening?
* When you click on the shuttle menu for Dubby What do you expect to happen?

**Comment by highacid** [comment]
Hi

http://hastebin.com/xejejopuho.json

here is my file Dubby is a DUB SIREN APP. What I do is this, I go to Shuttle > Settings > Edit, and opens me the Dubby APP instead of anything else.

**Comment by thshdw** [comment]
Ah, so it seems that that your dubby app is the default for .json files. Control click on your .json file and in the ```Always open with``` menu change the application to the app you want to open the .json file. 

Alternatively you could specify vi or nano or some other terminal based app open the .json file
```"editor": "vim",```
