### ISSUE TITLE
Sort items alphanumerically

### ISSUE THREAD

**Issue by PetaByet** [fitztrev/shuttle#203]
Hello,

Been trying to add the following items in the list: `50, 100, 200`, but they get sorted like so: `100, 200, 50`. Adding a "0" in front of the 50 appears to be the only option though very unpreferable.

This does not only apply to numbers but also other numerical items such as IP addresses.

Can we make a directive like this: `"Sort": "alpha"`, with options such as alpha (alpha numeric), natural, string length (or even random...)?

Alternatively an option to disable auto-sort, so items appear in the exact order as they are placed in the json config file.

Thanks!

**Comment by thshdw** [comment]
@PetaByet Hello, I'm going to close this issue and refer you to #117 where there is a discussion regarding this topic.
