### ISSUE TITLE
 Do you have an example for AWS

### ISSUE THREAD

**Issue by thshdw** [fitztrev/shuttle#204]
Asked by @Rainer-Lang

@thshdw Do you have an example for AWS? Where I have to use the pem-file?

**Comment by thshdw** [comment]
Hello, 
I don't have AWS account but this should work...
```"cmd": "ssh -i /path-to/my-key-pair.pem ec2-user@ec2-111-11-111-1.compute-1.amazonaws.com"```

**Comment by thshdw** [comment]
@Rainer-Lang did this work for you?

**Comment by frazei** [comment]
That's my configuration and it's working good:
{"name": "server.compute.amazonaws.com",
"cmd": "ssh -i ~/.ssh/aws.pem ubuntu@1.2.3.4"}

**Comment by prasenjithaty** [comment]
But tab names do not work.

**Comment by thshdw** [comment]
@petethepig something like this should make a tab name for you.
```
            {
              "cmd": "ssh -i ~/.ssh/aws.pem ubuntu@1.2.3.4"
              "inTerminal": "tab",
              "name": "server.compute.amazonaws.com",
              "theme": "basic",
              "title": "title of tab"
            }
```
