### ISSUE TITLE
Hyper Support

### ISSUE THREAD

**Issue by marc1404** [fitztrev/shuttle#205]
Would it be difficult to add support for usage with the Hyper Terminal?
Link: https://hyper.is/

**Comment by thshdw** [comment]
See #190 When applescript support is added in that app it may be possible.

**Comment by thshdw** [comment]
I did some digging in the electron issues and found this. https://github.com/electron/electron/issues/4418 seems that this is not happening anytime soon.

**Comment by marc1404** [comment]
Thanks @thshdw
Sorry for opening a duplicate issue, should have done some digging myself.

**Comment by thshdw** [comment]
@marc1404 No worries.
