### ISSUE TITLE
Groups with multiple servers

### ISSUE THREAD

**Issue by riorii** [fitztrev/shuttle#207]
The idea is having an item that when you click on it, it launch a group of tabs with different servers:

Example:

"name": "Group of Servers"
"cmd": "ssh server1 | ssh server2 | ssh server3"

This will result in 3 different tabs, with ssh sessions on server 1, 2 and 3.

I hope it's clear!

Thanks!

**Comment by thshdw** [comment]
Hello @riorii 
The discussion for this topic is in #172 closing this issue. Please continue the discussion in #172
Thanks!
