### ISSUE TITLE
Add support for writing settings in YAML format

### ISSUE THREAD

**Issue by behrangsa** [fitztrev/shuttle#208]
IMHO, JSON is not very convenient as a configuration file format. It also has features that while can be hacked around in JSON, is not supported by JSON (e.g. multi-line strings, comments, etc.).

Even AWS has started supporting YAML for CloudFormation. :)

**Comment by thshdw** [comment]
@behrangsa I'm going to quote @fitztrev from #6 

> The nice thing about creating a tool for developers is you can get away with telling them to edit a JSON file to change settings. Not exactly something you could do with any other sort of consumer app. :)

Fast forward 5 years.  Shuttle is a fairly popular app with a lot of users. Some of those users have made their own apps that read the shuttle.json file see https://github.com/hendricius/shuttle-cli 

Switching to YAML would break these integrations. 

I suppose that shuttle could support both YAML and JSON but I don't see the point in doing this. With that said if someone wants to fork > make new branch > add this feature > submit a pull request; I would approve it as long its 1 to 1 support to the feature set in JSON. This feature works in YAML but not in JSON would be bad for the project.
