### ISSUE TITLE
Support for Hyper

### ISSUE THREAD

**Issue by zerostyle** [fitztrev/shuttle#210]
Would be nice if I could open projects with Hyper.

https://hyper.is

**Comment by dominictayloruk** [comment]
Any news on this?

**Comment by marc-antoinepelletier** [comment]
I'd love to have it as well !

**Comment by JayHoltslander** [comment]
+1

**Comment by thshdw** [comment]
Last I checked Hyper did not support applescript https://github.com/fitztrev/shuttle/issues/205

**Comment by thshdw** [comment]
if hyper supports applescript I can look into supporting it.
