### ISSUE TITLE
can remember password?

### ISSUE THREAD

**Issue by Suzhida** [fitztrev/shuttle#214]

**Comment by dongyee** [comment]
i think can't yet .

**Comment by JeromeSuz** [comment]
u can use sshpass

**Comment by ivuorinen** [comment]
As we are using default `ssh`, this can be solved with some `.ssh/config` settings.

http://nerderati.com/2011/03/17/simplify-your-life-with-an-ssh-config-file/

**Comment by thshdw** [comment]
@Suzhida Please see https://github.com/fitztrev/shuttle/issues/146
