### ISSUE TITLE
script to ssh auto connect - script must to have

### ISSUE THREAD

**Issue by fmgdias** [fitztrev/shuttle#215]
Tired of typing the login password? Is the network slow? Use this script that auto-connects the ssh console.

Usage:
./ssh_console.sh 127.0.0.1
./ssh_console.sh 127.0.0.1 username userpass
./ssh_console.sh 127.0.0.1 username userpass rootpass

Check This:
[ssh_console.txt](https://github.com/fitztrev/shuttle/files/1032421/ssh_console.txt)

**Comment by rafkon1990** [comment]
or you can use sshpass and type 
`"cmd": "sshpass -p mypassword ssh -p 22 username@hostname"`

**Comment by stacksjb** [comment]
Yup, I use sshpass. You can also utilize an ssh file so it is not output to the command line.

**Comment by thshdw** [comment]
Thanks @rafkon1990 and @stacksjb sshpass is the solution here.
