### ISSUE TITLE
Is there support for a "tabColor" tag?

### ISSUE THREAD

**Issue by ximbal** [fitztrev/shuttle#216]
I want to change the color of the tab, for denoting production env from staging, so production tabs would be red and the staging ones from any other color, is this available on the json file?

**Comment by thshdw** [comment]
@ximbal https://github.com/fitztrev/shuttle/wiki/Command-Settings there is a theme option. using this you can change the theme of the terminal to any color you want

**Comment by thshdw** [comment]
@ximbal I think what you want to accomplish can be done with themes. So you make a terminal theme for ```production``` and you make another for ```env``` then using the Command settings you set the theme in the JSON settings with the command.
