### ISSUE TITLE
Iterm2 opening a new window when selected to open a tab

### ISSUE THREAD

**Issue by vinitkhandagle** [fitztrev/shuttle#217]
Iterm2 is opening a new window when I select the option to open a new tab. I tried finding settings for this but I am unable to set it anywhere. Whenever I select a "newtab" option from the menu it keeps opening new windows rather than a tab in the current window.

How do I get it to open a newtab in the current window?. 

Iterm2 Version: Build 3.0.15

**Comment by rafkon1990** [comment]
Try option:   `"inTerminal": "tab"`

**Comment by thshdw** [comment]
```"inTerminal": "tab"``` should work for you. Please re-open if this is not the case
