### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Tensho** [fitztrev/shuttle#220]
Thank you very much for this wonderful project 🙇  Please add `CHANGELOG.md` file where users and contributors could find changes for specific version of the application.

http://keepachangelog.com/en/1.0.0

**Comment by Tensho** [comment]
PING

**Comment by thshdw** [comment]
I put changes in the release section https://github.com/fitztrev/shuttle/releases but I can see the need for the log. I'll start this.

**Comment by thshdw** [comment]
This now exists in the master branch. Thanks!
