### ISSUE TITLE
Support two shuttle.json config files

### ISSUE THREAD

**Issue by Tensho** [fitztrev/shuttle#221]
Paranoid in me thinks that it will be very convenient to  keep **global config file** (`editor`, `launch_at_login`, `terminal`) aside of **hosts configuration file(s)** (`hosts`) . Basically, Shuttle already has segregation of global and command configurations inside. But separate files allow to keep common part under VCS and host commands with sensitive info out of repository, particularly  server IP addresses. 

Of course I could create custom shell functions, extract sensitive commands there and just referencing to them in `shuttle.json`, for example. But it seems to me lots of software allow to configure at global and local levels and `shuttle` deserves to be in row with them ^_^

Does it make sense?

**Comment by Tensho** [comment]
PING

**Comment by teopost** [comment]
The project is dead!

**Comment by thshdw** [comment]
@Tensho What would be the benefit of having them in separate files?

**Comment by Tensho** [comment]
I could commit project-specific commands (servers IP) to VCS, share them with colleagues and leave my personal commands out of VCS.

**Comment by thshdw** [comment]
Would multiple configs solve this issue, I think it would. See here https://github.com/fitztrev/shuttle/issues/162 if what is proposed in 162 solves your issue i'll mark this duplicate.

**Comment by Tensho** [comment]
Kind of that. But I'd like to emphasize on multiple `.json` config files (and their merge), not `ssh_config` files. I guess this is `ssh` client responsibility to gather `ssh_config`s, not `shuttle`'s.

**Comment by thshdw** [comment]
Okay. I'll change the title of this issue to "Support two shuttle.json configuration files"

**Comment by thshdw** [comment]
Feature added in https://github.com/fitztrev/shuttle/pull/246

**Comment by Tensho** [comment]
Thank you 🙇
