### ISSUE TITLE
Re-arranging the menu items

### ISSUE THREAD

**Issue by philippetev** [fitztrev/shuttle#222]
Currently, the app arranges the items alphabetically. Maybe it would be better if some kind of ID is added as a parameter or simply the app can just show them in the same order they are written in the config file?

**Comment by linkyfish** [comment]
SDFSDFRTGTTTFRRTTR

**Comment by linkyfish** [comment]
SDFSDFRTGTTTFRRTTR

2017-08-31 14:54 GMT+08:00 Philip Petev <notifications@github.com>:

**Comment by onacit** [comment]
I also want those items listed as they are written.

Let's say I have some connections for servers along their environments.

```
some service
    development
    integration
    staging
    production
```

And the `production` menu appears before the `staging` menu.

**Comment by thshdw** [comment]
This is a good idea. We should have some kind of sorting ability.
