### ISSUE TITLE
Close window when typing "exit" from SSH connection

### ISSUE THREAD

**Issue by chrisfromredfin** [fitztrev/shuttle#223]
Prior to Shuttle, I used to use Safari SSH bookmarks in a folder. The only thing I prefer about this method over Shuttle, is that when I typed 'exit' from the SSH connection, it would close the window. With Shuttle windows, I have to type exit, and then exit again. 

Is this something that could be supported with current config somehow, and if not, would you consider this as a feature request? Admittedly, I'm not sure how the process spawning works or if there's an iTerm option I could pass, etc.

**Comment by JayHoltslander** [comment]
I just arrived here while searching for info on this exact thing.

I have the shuttle command:
``"cmd": "echo && sudo dscacheutil -flushcache && sudo killall -HUP mDNSResponder && exit",`` that I hoped would close the terminal window automatically after running but does not.

A way to do this would be awesome.

**Comment by JayHoltslander** [comment]
@ww7 I'm not quite clear on your answer. Are you saying that appending ``&& exec sleep 1`` should result in the terminal window closing after? (I tried that and it did not.)

**Comment by ww7** [comment]
@JayHoltslander I suggest to use iTerm
Instead for terminal for both `exit` and `exec sleep <wait seconds>` need to set option, see [OSX - How to auto Close Terminal window after the “exit” command executed.
](https://stackoverflow.com/questions/5560167/osx-how-to-auto-close-terminal-window-after-the-exit-command-executed)

**Comment by chrisfromredfin** [comment]
Wow, didn't occur to me to just add "&& exit" (or "; and exit" for fish shell)! That works for me. 

So, if the "&& exit" trick isn't working for you, then I agree you probably just need to set "close window if shell exited cleanly" option in Terminal preference.
