### ISSUE TITLE
No more fully working under macOS High Sierra

### ISSUE THREAD

**Issue by bligny** [fitztrev/shuttle#224]
A (minor) problem is appearing when running under macOS High Sierra:
"inTerminal: new" now always opens in a new tab of existing window (and not in a new terminal window)

**Comment by rafkon1990** [comment]
For me work with:
`"inTerminal": "new"` - open in new window
`"inTerminal": "tab"` - open in same window in new tab

**Comment by bligny** [comment]
I finally found the reason: it was a consequence of my dock settings. 
The option "_Prefer tabs when opening documents_" was set to "_Always_". Everything is working fine again as soon as I switch this option to "_Manually_".
Sorry for the noise :-(
