### ISSUE TITLE
Running with Hyperterm

### ISSUE THREAD

**Issue by juanjosezg** [fitztrev/shuttle#225]
Im trying to run with Hyper.js 

i change this:

  "launch_at_login": true,
  **"terminal": "/Applications/Hyper.app",**
  "iTerm_version": "nightly",
  "default_theme": "Homebrew",
  "open_in": "new",  
  "show_ssh_config_hosts": false,
  "ssh_config_ignore_hosts": [  ],
  "ssh_config_ignore_keywords": [  ],
  "hosts": [

but doesn't work, any idea?

**Comment by philippetev** [comment]
That won't work, the paths to the terminals (Terminal.app, ITerm.app etc.) are hard-coded in the app and their designations are used as a value here instead.

**Comment by thshdw** [comment]
Last I checked hyper does not have applescript support https://github.com/fitztrev/shuttle/issues/205

**Comment by thshdw** [comment]
if hyper supports applescript I can look into supporting it.
