### ISSUE TITLE
Config to run command after login

### ISSUE THREAD

**Issue by debabratakarfa** [fitztrev/shuttle#227]
Is that possible to config .shuttle.json that will run command i.e. cd or etc after login to server

{
			"Submenu 2": [
				{
					"name": "Submenu Item #2.1",
					"cmd": "ssh username@dev.example.net -p 3000; cd /www/bla/foo"
				}
			]
},

or

{
			"Submenu 2": [
				{
					"name": "Submenu Item #2.1",
					"cmd": "ssh username@dev.example.net -p 3000;",
 "cmd": "cd /www/bla/foo"
				}
			]
},

**Comment by quzhongqiang** [comment]
no use

**Comment by quzhongqiang** [comment]
My way of writing is this--- "cmd":"sshpass -p xxx ssh -o StrictHostKeyChecking=no -p 14816 appman@10.230.39.8; cd /opt" ---but your opinion isn't effective.

**Comment by thshdw** [comment]
@debabratakarfa version 1.2.3 added ```"inTerminal": "current"``` using this you can add your ```cd /www/bla/foo``` command 

So you would have one entry in shuttle to connect to your system and then another entry to run your command.
