### ISSUE TITLE
加上代码后无法最小化终端窗口

### ISSUE THREAD

**Issue by man2018** [fitztrev/shuttle#228]
osascript -e "tell application \"Terminal\" to set miniaturized of every window to true"

加上这句代码后报错，也无法最小化终端窗口，大神我应该怎么搞呢

**Comment by thshdw** [comment]
I'm not sure what you want to accomplish. Run a command and then minimize the window right after?

**Comment by thshdw** [comment]
Closing for now as I'm not sure what this is about. If someone could help with the translation that would great.
