### ISSUE TITLE
How many of you are still using iTerm 2.14? 

### ISSUE THREAD

**Issue by thshdw** [fitztrev/shuttle#233]
We have applescripts for various versions of iTerm

```"iTerm_version": "legacy"```, targeting iTerm 2.14
```"iTerm_version": "stable"```, targeting new versions of iTerm
```"iTerm_version": "nightly"```,targeting only the nightly build of iTerm

is anyone still using iTerm 2.14 ?

**Comment by thshdw** [comment]
I ask because I'm thinking about dropping support for iTerm 2.14. My guess is that no one is using it anymore but I wanted to get an idea from the user base.

**Comment by JJClements** [comment]
Nope, always using the latest here - 3.1.6 at this time.

**Comment by thshdw** [comment]
Removing iTerm 2.14 support. The iTerm_version legacy option was useful during the 3.x release and gave users some time to migrate.
2.x is no longer maintained, as such I’m removing its support.
