### ISSUE TITLE
Cannot arrange order of commands

### ISSUE THREAD

**Issue by ledlamp** [fitztrev/shuttle#240]
I configured the "hosts" array in a specific order but the menu list does not respect that order and the listings appear to just be arranged alphabetically. I would prefer if the commands are listed in the same order as they are in the config.

**Comment by thshdw** [comment]
see https://github.com/fitztrev/shuttle/pull/234 the ability to change sorting is in the code base.

**Comment by thshdw** [comment]
@ledlamp you left a confused emoji. In the next version you will have the option to sort the menu items in any way you want. This work is done in #234 but I've not compiled a release yet. Hope that clears it up 😄
