### ISSUE TITLE
Allow for shuttle.inTerminal in ~/.ssh/config

### ISSUE THREAD

**Issue by Sudmota** [fitztrev/shuttle#247]
Hey there !

Great work with Shuttle.
Are you considering something like adding a `# shuttle.inTerminal` instruction ?

Example:

```
Host my_machine
  # shuttle.name = path/to/resource
  # shuttle.inTerminal = current <------------------------
  Hostname 10.1.2.3
```

Best regards !

**Comment by thshdw** [comment]
If we did do this we would have to support all the options. 
```
shuttle.name
shuttle.inTerminal
shuttle.theme
shuttle.title
```
Unless the other contributors have concerns I'll add it to the to do list.

**Comment by thshdw** [comment]
Seems that this is a duplicate, see #161
