### ISSUE TITLE
Request: drop SSH from the tag line 

### ISSUE THREAD

**Issue by thshdw** [fitztrev/shuttle#248]
@fitztrev 
The current tagline reads ```A simple SSH shortcut menu for macOS```

Perhaps we should drop SSH
```A simple shortcut menu for macOS```

The project has evolved and you can use it for opening websites, folders, and a number of other things.  
Thoughts?

**Comment by lindseydiloreto** [comment]
**^ This.** I had no idea how powerful this app was until I actually installed it and flipped through the Wiki. You should _definitely_ let people know that it does much more than just SSH, you're vastly understating what this app is capable of.

<img width="565" alt="2019-01-24 at 3 30 31 pm" src="https://user-images.githubusercontent.com/5309692/51715430-87f1ed00-1fed-11e9-9446-0fadde216c60.png">

^ The "About" statement above is blatantly false.

This app has been a lifesaver for me! Thank you for all of the hard work. 🍺

**Comment by lindseydiloreto** [comment]
Definitely better, though still pretty vague. Maybe something like this?...

`A simple shortcut menu for custom shell commands`

The "macOS" part is implied (via screenshots and otherwise), so you probably don't need to reiterate it in the tagline.

Thoughts?

**Comment by thshdw** [comment]
> The "macOS" part is implied (via screenshots and otherwise), so you probably don't need to reiterate it in the tagline.

Agree with this, it makes sense to drop macOS.

```A simple shortcut menu for custom shell commands``` 
This wouldn't be entirely true because it can open URL's in the default browser, or file paths in finder. Those wouldn't be shell commands.

**Comment by fitztrev** [comment]
👍 Good suggestion @thshdw 

Looks like the default sample json already includes some examples of it being used in this way. Maybe the next gif could highlight a couple different use cases (1 ssh and 1 other).

@lindseydiloreto Thank you for adding your voice. I never gave much thought to non-ssh uses of Shuttle. Great to hear it has been able to be adapted beyond that and that it helps so much. 🎉

**Comment by thshdw** [comment]
>I didn't realize that! How exactly does that work?

It uses NSURL to check the command to see if its a URL. If the command is detected as a URL it opens it in the default app
If you are curious about the back end see:

https://developer.apple.com/documentation/foundation/nsurl
and 
https://developer.apple.com/documentation/appkit/nsworkspace

to get this working just make your command a url example
```
      "cmd": "https://google.com",
      "name": "bookmark to google"
```

>My new favorite usage for it is to quickly spin up an existing Vagrant box...

nice!
```cd ~/Sites/my/vagrant/box && vagrant up```
in the next binary you can put this command in the background using ```screen``` and it wont open a terminal. 

I'm happy you like it. 😄

**Comment by lindseydiloreto** [comment]
>... you can put this command in the background using screen and it wont open a terminal

Brilliant, that's even better!

What an awesome little tool, keep up the great work! 🍺

**Comment by julien-c** [comment]
Would you be up for me pushing an LLM-assisted rewrite of Shuttle to modern Swift/Mac OS, @fitztrev?

Context: i'm changing laptop and don't want to have to build an Obj-C project:)

**Comment by fitztrev** [comment]
@julien-c yeah sure, what do you need from me?

I have a Mac but I don't use it anymore for server admin tasks where Shuttle would help. if I were to pick up development myself, I would use Tauri (I'm currently developing [another desktop app](https://github.com/lichess-org/broadcaster) with it) so that it could be cross platform. I actually would really like to use it on Linux 😃
