### ISSUE TITLE
support for include recursive ssh_config 

### ISSUE THREAD

**Issue by georgesnow** [fitztrev/shuttle#249]
I tried a couple different ways to see if i missing something, but the include parsing doesn't seem to read recursive ssh_configs

ssh_config:
Include config-d/\*/\*

inside directory ~/.ssh/config-d/

Personal (subdirectory)

-       homemachine (config file)

Work (subdirectory)

-        server-a (config file)
-        sever-b (config file)

etc...

**Comment by thshdw** [comment]
I need to compile a binary. Include support was added here https://github.com/fitztrev/shuttle/pull/238

**Comment by georgesnow** [comment]
I think I should clarify it will read one layer of recursive read. So my in configuration mine spans multiples layers with separate config files for each host.  But I will give it go again

**Comment by ergoz** [comment]
need same functionality. When new release will be published?
