### ISSUE TITLE
.shuttle.path not working

### ISSUE THREAD

**Issue by ledlamp** [fitztrev/shuttle#253]
As documented by https://github.com/fitztrev/shuttle/wiki/Settings-and-Configuration#json-path-change I created a file named `.shuttle.path` in my home directory using nano, first with the content `Dropbox/shuttle.json` (is the home directory the pwd?) then `~/Dropbox/shuttle.json`, and even `/Users/me/Dropbox/shuttle.json`, but it just doesn't work. Shuttle just shows nothing, or if a shuttle.json is present, uses that instead. It seems to not read the `.shuttle.json` file at all.
Edit: It seems that a valid `.shuttle.path` is breaking the program. I added the `.shuttle.path` with the full path while the `.shuttle.json` was still there. Shuttle seemed to still use the json. I removed the json file, then shuttle showed nothing. But then after putting the json file back and removing the path file, shuttle still does not show anything until I restart the program.

However, on a different mac with OS 10.14.3, the `.shuttle.path` works fine. My mac has OS 10.11.6, so maybe that has something to do with it?

**Comment by thshdw** [comment]
Hi @ledlamp 
I don't have access to 10.11.6, however this feature should work in this version. 
Maybe a permissions issue? Try deleting .shuttle.path and creating it using touch. 
While in your user account open a terminal and go to your user path 
cd /Users/me
then 
```touch .shuttle.path```
then ```nano .shuttle.path``` and add 
```/Users/me/Desktop/shuttle.json```
Then open shuttle and test.

**Comment by ledlamp** [comment]
Ok I pinpointed what the issue was. First of all it turns out **Shuttle only reads `.shuttle.path` at launch** so the program needs to be restarted for changes to take effect. Second, only absolute paths work. Paths using tilda `~/Dropbox/shuttle.json` or paths assuming home is the pwd `Dropbox/shuttle.json` do not work. So while I did try restarting the app I might not have done it with the absolute path. Now that I know these two things I have got it working.

**Comment by thshdw** [comment]
Thanks for the update. I'll make sure the wiki is updated accordingly

**Comment by ledlamp** [comment]
I just updated the wiki 😉

**Comment by thshdw** [comment]
I see that! Thank you!
