### ISSUE TITLE
Is it possible to support Native Apple Silicon?

### ISSUE THREAD

**Issue by goxofy** [fitztrev/shuttle#273]

**Comment by fhefh2015** [comment]
Switch For Your Command - a shortcut menu to run the shell command | Product Hunt 
https://www.producthunt.com/posts/switch-for-your-command 
------
I found this app, similar to shuttle
I used iMobie M1 App Checker to check and it is supported by M1
Hope this helps

![image](https://user-images.githubusercontent.com/14891797/113463029-54753d80-9456-11eb-807c-289758617536.png)

**Comment by goxofy** [comment]
@fhefh2015 look nice! Thank you very much!

**Comment by goxofy** [comment]
@fhefh2015 I found some bugs(features) with the Switch.
1. auto sync，this feature should be closed because maybe someone will write ssh password in cli by Expect
2. doesnot support secondary menu

**Comment by dieskim** [comment]
I created a basic app that does what Shuttle did but is built for macOS Ventura and above - https://github.com/dieskim/MenuBarSSHCommands
