### ISSUE TITLE
Feature: read .ssh/known_hosts for servers

### ISSUE THREAD

**Issue by bytesplit** [fitztrev/shuttle#30]
As I read on MacUpdate, some users are having issues with the json format config. Seems to be to complex for whatever reason.

But you could add a submenu with text 'Known hosts' or 'Recently visited' which is not 100% accurate. This menu could be autofilled by reading the host entries in the known_hosts file. Guess this could work like dream for those noobs.

Perhaps, then you also need to think about one or two new keys in the config. Like a boolean for read_sshconfig and read_knownhosts.

**Comment by fitztrev** [comment]
Thank you for the suggestion. This may be considered for a future release.
