### ISSUE TITLE
Runs command in an already opened terminal window

### ISSUE THREAD

**Issue by roldershaw** [fitztrev/shuttle#32]
Hi,

A couple of times I've noticed after one terminal tab has been opened occasionally when opening up another the app will actually run the command inside an already open tab.

I can't seem to work out why it occurs but I've seen it happen randomly a couple of times now.

Rory

**Comment by thshdw** [comment]
This issue should be resolved in the latest release [v1.2.3](https://github.com/fitztrev/shuttle/releases/tag/v1.2.3) Make sure that your using iTerm 2.14 (Stable) Or the Latest iTerm Nightly
