### ISSUE TITLE
icon

### ISSUE THREAD

**Issue by mjbaldwin** [fitztrev/shuttle#46]
Awesome little app. Super-kudos.

The icon is rather indistinct and blobby in the menubar, at such a small size. Let me know if you'd like any help with it.

I'd personally prefer just a terminal rectangle with a lock icon inside to represent SSH or whatnot. But the rocketship is cool too, since it's all about "launching" -- maybe thinner and vertical would be clearer, instead of fat and tilted.

**Comment by fitztrev** [comment]
Closing for now, though open to further suggestions for improvement.
