### ISSUE TITLE
tip/request: executing shell scripts

### ISSUE THREAD

**Issue by mjbaldwin** [fitztrev/shuttle#48]
I have a number of shell scripts I wanted to add shortcuts too, but adding a command like

    "cmd": "/path/to/script.sh"

doesn't launch anything at all. Fortunately,

    "cmd": "eval \"/path/to/script.sh\""

does. Not sure if this is a bug or a feature. But, just so everyone knows, eval works.

**Comment by thshdw** [comment]
@mjbaldwin I use shell scripts all the time. You have you make your script executable like this:

```
chmod +x /path/to/script.sh 
```
Then you could "cmd": "/path/to/script.sh" as in your example. Or...
You could run the script through sh like this:
```
"cmd": "sh ~/Documents/scripts/myScript.sh"
```
