### ISSUE TITLE
Support for multiple hosts in ssh config and / or ignore ssh config file.

### ISSUE THREAD

**Issue by mafredri** [fitztrev/shuttle#49]
Only the first host is picked out of a line with multiple hosts in the ssh config.

For example:

    Host test.google.com secret.google.com

Only test.google.com would be visible.

I would also like to order some of my servers in ssh config into sub menus, and to be able to do this you would either need to ignore the ssh config or provide some syntax in ssh config that creates submenus in shuttle.

**Comment by fitztrev** [comment]
Closing this issue for now. Please open a new one if the issue has not been resolved.
