### ISSUE TITLE
Does not run SSH command in iTerm using ZSH

### ISSUE THREAD

**Issue by rickhanlonii** [fitztrev/shuttle#5]
Great project!   
  
I just installed, configured iTerm as the terminal, and added a host. When clicking that host in the menu, iTerm opens fine, but the ssh command does not run; I just get an open local terminal.   
  
I suspect this is because I'm using ZSH as my shell, but I haven't looked into the code to verify. Here's my config file (ssh user and ip masked):  
  
    {
	  "_comment": "Valid terminals include: 'Terminal.app' or 'iTerm'",
	  "terminal": "iTerm",
	  "hosts": [
		  {
			"name": "App1",
			"cmd": "ssh user@192.168.1.1"
		  }
	  ]
    }

**Comment by daften** [comment]
I also have the behaviour with iterm running with no open windows, that the ssh session is not launched (no new iterm window is opened).

On a sidenote, when iTerm is closed, it works, but then I have a blank tab and a tab for the ssh session.

**Comment by AnatolyAstapov** [comment]
work

ln -s /Applications/iTerm.app/Contents/MacOS/iTerm /usr/bin/iTerm
chmod +x /usr/bin/iTerm

in config 
"terminal": "iTerm",

**Comment by thshdw** [comment]
@rickhanlonii  Please try in the latest [release](https://github.com/fitztrev/shuttle/releases/tag/v1.2.3) Make sure you have a current version of iTerm Stable or Nightly
