### ISSUE TITLE
Feature - make a bonjour group

### ISSUE THREAD

**Issue by Chaosbit** [fitztrev/shuttle#56]
Hey,
I just installed your App and like it very much.
So I hope I don't miss an existing option.

What would be really nice to have is an option to add all bonjour announced ssh servers to an group, so you don't need to add configs for you local servers...

Kind regards

**Comment by fitztrev** [comment]
I'm not familiar with Bonjour. In the future, I'd like to be able to dynamically update the list (for example, pull a list of all your ec2 instances and display them). So this might be in line with that. When that time comes, we can look at adding support for Bonjour as well. Thank you for the idea and glad you like Shuttle!
