### ISSUE TITLE
Suggestion: Allow "real" comments in the JSON config

### ISSUE THREAD

**Issue by getify** [fitztrev/shuttle#6]
I have a little project that takes an otherwise JSON file but that also has JS style comments like /* .. */ or // ... and strips them, before you pass them to a JSON parser. I'm assuming internally you're using a JSON parser to consume the config file. It's specifically built for apps which use JSON not as a transmission format but more as a static file format (for config, etc).

My suggestion is we port [JSON.minify](http://github.com/getify/JSON.minify) to the language this app is written in, so you could use it on the JSON config before parsing, which would allow friendlier comments in the config file than the "_comments" convention.

Thoughts?

**Comment by fitztrev** [comment]
Sorry about keeping this issue open for so long, guys. I'm going to close this. IMO, it's just not worth adding the extra code necessary to support it and then maintain it over time. The current `_comment` key system is sufficient.
