### ISSUE TITLE
Double Quote on Password

### ISSUE THREAD

**Issue by cucanunes** [fitztrev/shuttle#64]
Few passwords generated automatic by servers contain non common characters including double quotes.
I did not figured out how to include it in ssh commmand like:

"cmd": "ssh username@example.net -p r%6&#"$ku8"

I tried to use \" 
and 
"cmd": 'ssh username@example.net -p r%6&#"$ku8'

both without success.

**Comment by fitztrev** [comment]
I'd recommend using ssh keys.

Though it appears to be an escaping issue. Check it out on [explainshell](http://explainshell.com/explain?cmd=ssh+username%40example.net+-p+r%256%26%23%22%24ku8). Also, the `-p` flag is to specify port.
