### ISSUE TITLE
Show version in an about dialog

### ISSUE THREAD

**Issue by mjbaldwin** [fitztrev/shuttle#70]
I wanted to see if you'd updated Shuttle... but I can't figure out any way to tell what version I currently have installed.

I don't know if you're still working on Shuttle at all, but if you are, maybe have "About" show a simple dialog with the version, and a link to the website, instead of opening the website directly.

**Comment by thshdw** [comment]
Hello, 
I have added an about window in this pull request https://github.com/fitztrev/shuttle/pull/100

**Comment by fitztrev** [comment]
Added in #100. Thanks! :smile:
