### ISSUE TITLE
Shuttle sends commands to windows that are not terminals

### ISSUE THREAD

**Issue by tylerhenthorn** [fitztrev/shuttle#80]
I have found way to reliably reproduce the behavior since originally creating this issue, and am editing to reflect that: 

1) Open iTerm2 window on Desktop 1.
2) Open iTerm2 window on Desktop 2.
3) Bring focus to random non-terminal application on Desktop 1. 
4) Use shuttle via the menu on Desktop 1.

The expected behavior is that shuttle grabs an iTerm2 window, creates a new tab, and sends commands into the new tab. 

In this case, Shuttle will grab the iTerm2 window on Desktop 1, and send the commands into the current tab. This tab could contain anything, such as an open IRSSI session.

**Comment by thshdw** [comment]
@tylerhenthorn Could you test using the [latest release](https://github.com/fitztrev/shuttle/releases/tag/v1.2.3) The applescript parts have bee changed. Make sure you have the latest iTerm Stable or Nightly
