### ISSUE TITLE
Running command with no iTerm window fails

### ISSUE THREAD

**Issue by codisms** [fitztrev/shuttle#82]
If I have iTerm running but with no windows open, I can't run anything from Shuttle.  A window has to be open.

**Comment by thshdw** [comment]
@codisms @dasraab I was getting the same issue. Open iTerm run a command, then later close all iTerm windows. iTerm stays open in the background but there are no windows open. When you try to run the next shuttle command nothing happens. I was able to get around this in https://github.com/fitztrev/shuttle/pull/102 by adding reopen to the apple script command.

**Comment by thshdw** [comment]
Complete! See release [v1.2.3](https://github.com/fitztrev/shuttle/releases/tag/v1.2.3)
