### ISSUE TITLE
Spaces in Directories/cmd

### ISSUE THREAD

**Issue by srajkovic** [fitztrev/shuttle#83]
If there is a space in the cmd key's value (such as in ```-i /directory/ssh keys/``` to specify a key to use), it is not escaped when being sent to Terminal.app, so the connection attempt fails, but if you manually escape it you get an ```error parsing config``` error in the Shuttle menu bar menu.

**Comment by nofont** [comment]
I have the same issue with any escaped character.

**Comment by fitztrev** [comment]
Could you please paste your config entry that causes the problem?

**Comment by fitztrev** [comment]
Going to close this ticket for now, just to clean things up. But please open a new issue if you still have problems. Also, see #86 where I had to just escape a few additional characters to get it working.

**Comment by nofont** [comment]
Sounds good. I'll test and open new issue if somethings now working. Thanks a lot!
