### ISSUE TITLE
Shuttle icon only appears on main monitor

### ISSUE THREAD

**Issue by hannemanp** [fitztrev/shuttle#85]
I'm running OSX 10.10 and use two external monitors with my MBPr.  The shuttle icon only appears on my main screen, not on either of the auxiliary screens.

**Comment by fitztrev** [comment]
@blazeworx I think you're running 2 external monitors on your MBP... Any chance you could look into this? Do you see the same issue?

**Comment by blazeworx** [comment]
@fitztrev I have yet to test it on 10.10 with multiple monitors but on 10.9 on rMBP screen + 2x external monitors (3 in total) it works correctly. Will post an update later today after I try to recreate on 10.10

**Comment by thshdw** [comment]
@hannemanp I don't have this issue in 10.11 using the latest release [v1.2.3](https://github.com/fitztrev/shuttle/releases/tag/v1.2.3). If its still a problem please reopen :smile:
