### ISSUE TITLE
Shuttle doesn't open iTerm2 in Yosemite

### ISSUE THREAD

**Issue by philippetev** [fitztrev/shuttle#94]
The title says it all - Shuttle doesn't open automatically the iTerm2 app in OS X Yosemite. Haven't seen such problem in Mavericks. If I open iTerm2 manually, then it opens a new tab in the iTerm's windows and starts the ssh connection.

**Comment by danvideo** [comment]
Same here, but worse.  After Yosemite upgrade (OS X 10.10.1), Shuttle does not open iTerm 2 v2.0.2, build 2221 - at all.  It won't start app or create tabs/windows when app is started.  This was fine before upgrade.  Shuttle can still open Terminal fine.

**Comment by jens-nedal** [comment]
Same here. iTerm v 2.0.0.2xxx is not opening through Shuttle.

**Comment by sharonleon** [comment]
same...

**Comment by thshdw** [comment]
see pull request https://github.com/fitztrev/shuttle/pull/102
~~~
Unified the terminal open behavior by adding "reopen" in the apple script settings... When using iTerm if you closed all tabs and then the app; the next command would not open. When using terminal, if it were minimized a new menu item opened in a new window, instead of a new tab like iTerm. reopen solves both issues.
~~~

**Comment by bingalls** [comment]
Works for me. Do you include in your ~/.shuttle.json : 
```
{
	"terminal": "iTerm"
}
```

**Comment by JisuPark** [comment]
same here. i uses iTerm v 2.1.4  and Mac OS X 10.10.5
@bingalls I already did but not works.

**Comment by thshdw** [comment]
If the latest release [v1.2.3](https://github.com/fitztrev/shuttle/releases/tag/v1.2.3) does not fix this please let me know. :smile:

**Comment by taomaree** [comment]
shuttle v1.2.4 cannot open iTerm on EL Caption.
shuttle v1.2.0 can open iTerm on EL Caption.

OS: EL Caption 10.11
iTerm: 2.1.4 (latest)

**Comment by thshdw** [comment]
@taomaree Make sure that your shuttle.json file has the following setting ```"iTerm_version": "stable",```

**Comment by taomaree** [comment]
@thshdw thanks very much.
It's OK after adding  `"iTerm_version": "stable",`

**Comment by thshdw** [comment]
@taomaree You're Welcome! Thanks for the update!
