### ISSUE TITLE
Feature: Open all servers in submenu in new window with split panes in iTerm

### ISSUE THREAD

**Issue by afhole** [fitztrev/shuttle#97]
I would very much like to open all servers in a submenu with one click (ideal for opening sessions on every node in a cluster)

Ideally this would be in a new (iTerm) window in split-panes if possible (maybe configurable horizontal/vertical panes or tabs)

**Comment by fitztrev** [comment]
Thank you for the suggestion. For now, I'd recommend looking into using a combination of `tmux` and `mosh` or `autossh` to manage a situation like that. You could then create a Shuttle menu item that automatically starts that tmux session in a new terminal window.
